// Code generated by go-swagger; DO NOT EDIT.

package v1recipe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AttachRecipeReader is a Reader for the AttachRecipe structure.
type AttachRecipeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AttachRecipeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewAttachRecipeDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewAttachRecipeDefault creates a AttachRecipeDefault with default headers values
func NewAttachRecipeDefault(code int) *AttachRecipeDefault {
	return &AttachRecipeDefault{
		_statusCode: code,
	}
}

/*
AttachRecipeDefault handles this case with default header values.

successful operation
*/
type AttachRecipeDefault struct {
	_statusCode int
}

// Code gets the status code for the attach recipe default response
func (o *AttachRecipeDefault) Code() int {
	return o._statusCode
}

func (o *AttachRecipeDefault) Error() string {
	return fmt.Sprintf("[POST /v1/recipe/attach][%d] attachRecipe default ", o._statusCode)
}

func (o *AttachRecipeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
