// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AzureCertificateResponse azure certificate response
// swagger:model AzureCertificateResponse
type AzureCertificateResponse struct {

	// certificate
	Certificate string `json:"certificate,omitempty"`

	// expiration
	Expiration int64 `json:"expiration,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this azure certificate response
func (m *AzureCertificateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureCertificateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureCertificateResponse) UnmarshalBinary(b []byte) error {
	var res AzureCertificateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
