// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AzureEnvironmentParameters azure environment parameters
// swagger:model AzureEnvironmentParameters
type AzureEnvironmentParameters struct {

	// Azure resource group parameters.
	ResourceGroup *AzureResourceGroupV1Parameters `json:"resourceGroup,omitempty"`
}

// Validate validates this azure environment parameters
func (m *AzureEnvironmentParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResourceGroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AzureEnvironmentParameters) validateResourceGroup(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceGroup) { // not required
		return nil
	}

	if m.ResourceGroup != nil {
		if err := m.ResourceGroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resourceGroup")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AzureEnvironmentParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureEnvironmentParameters) UnmarshalBinary(b []byte) error {
	var res AzureEnvironmentParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
