// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GcpEnvironmentV1Parameters gcp environment v1 parameters
// swagger:model GcpEnvironmentV1Parameters
type GcpEnvironmentV1Parameters struct {

	// Parameter for GCP resource encryption.
	GcpResourceEncryptionParameters *GcpResourceEncryptionV1Parameters `json:"gcpResourceEncryptionParameters,omitempty"`
}

// Validate validates this gcp environment v1 parameters
func (m *GcpEnvironmentV1Parameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGcpResourceEncryptionParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GcpEnvironmentV1Parameters) validateGcpResourceEncryptionParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.GcpResourceEncryptionParameters) { // not required
		return nil
	}

	if m.GcpResourceEncryptionParameters != nil {
		if err := m.GcpResourceEncryptionParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gcpResourceEncryptionParameters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GcpEnvironmentV1Parameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GcpEnvironmentV1Parameters) UnmarshalBinary(b []byte) error {
	var res GcpEnvironmentV1Parameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
