// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlatformSSHKeysV1Response platform Ssh keys v1 response
// swagger:model PlatformSshKeysV1Response
type PlatformSSHKeysV1Response struct {

	// ssh keys
	SSHKeys map[string][]PlatformSSHKeyV1Response `json:"sshKeys,omitempty"`
}

// Validate validates this platform Ssh keys v1 response
func (m *PlatformSSHKeysV1Response) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSSHKeys(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlatformSSHKeysV1Response) validateSSHKeys(formats strfmt.Registry) error {

	if swag.IsZero(m.SSHKeys) { // not required
		return nil
	}

	for k := range m.SSHKeys {

		if err := validate.Required("sshKeys"+"."+k, "body", m.SSHKeys[k]); err != nil {
			return err
		}

		if err := validate.UniqueItems("sshKeys"+"."+k, "body", m.SSHKeys[k]); err != nil {
			return err
		}

		for i := 0; i < len(m.SSHKeys[k]); i++ {

			if err := m.SSHKeys[k][i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sshKeys" + "." + k + "." + strconv.Itoa(i))
				}
				return err
			}

		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlatformSSHKeysV1Response) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlatformSSHKeysV1Response) UnmarshalBinary(b []byte) error {
	var res PlatformSSHKeysV1Response
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
