// Code generated by go-swagger; DO NOT EDIT.

package v1dns

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDNSCnameRecordV1Params creates a new DeleteDNSCnameRecordV1Params object
// with the default values initialized.
func NewDeleteDNSCnameRecordV1Params() *DeleteDNSCnameRecordV1Params {
	var ()
	return &DeleteDNSCnameRecordV1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDNSCnameRecordV1ParamsWithTimeout creates a new DeleteDNSCnameRecordV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDNSCnameRecordV1ParamsWithTimeout(timeout time.Duration) *DeleteDNSCnameRecordV1Params {
	var ()
	return &DeleteDNSCnameRecordV1Params{

		timeout: timeout,
	}
}

// NewDeleteDNSCnameRecordV1ParamsWithContext creates a new DeleteDNSCnameRecordV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDNSCnameRecordV1ParamsWithContext(ctx context.Context) *DeleteDNSCnameRecordV1Params {
	var ()
	return &DeleteDNSCnameRecordV1Params{

		Context: ctx,
	}
}

// NewDeleteDNSCnameRecordV1ParamsWithHTTPClient creates a new DeleteDNSCnameRecordV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDNSCnameRecordV1ParamsWithHTTPClient(client *http.Client) *DeleteDNSCnameRecordV1Params {
	var ()
	return &DeleteDNSCnameRecordV1Params{
		HTTPClient: client,
	}
}

/*DeleteDNSCnameRecordV1Params contains all the parameters to send to the API endpoint
for the delete Dns cname record v1 operation typically these are written to a http.Request
*/
type DeleteDNSCnameRecordV1Params struct {

	/*Cname*/
	Cname *string
	/*DNSZone*/
	DNSZone *string
	/*Environment*/
	Environment *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) WithTimeout(timeout time.Duration) *DeleteDNSCnameRecordV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) WithContext(ctx context.Context) *DeleteDNSCnameRecordV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) WithHTTPClient(client *http.Client) *DeleteDNSCnameRecordV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCname adds the cname to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) WithCname(cname *string) *DeleteDNSCnameRecordV1Params {
	o.SetCname(cname)
	return o
}

// SetCname adds the cname to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) SetCname(cname *string) {
	o.Cname = cname
}

// WithDNSZone adds the dNSZone to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) WithDNSZone(dNSZone *string) *DeleteDNSCnameRecordV1Params {
	o.SetDNSZone(dNSZone)
	return o
}

// SetDNSZone adds the dnsZone to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) SetDNSZone(dNSZone *string) {
	o.DNSZone = dNSZone
}

// WithEnvironment adds the environment to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) WithEnvironment(environment *string) *DeleteDNSCnameRecordV1Params {
	o.SetEnvironment(environment)
	return o
}

// SetEnvironment adds the environment to the delete Dns cname record v1 params
func (o *DeleteDNSCnameRecordV1Params) SetEnvironment(environment *string) {
	o.Environment = environment
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDNSCnameRecordV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cname != nil {

		// query param cname
		var qrCname string
		if o.Cname != nil {
			qrCname = *o.Cname
		}
		qCname := qrCname
		if qCname != "" {
			if err := r.SetQueryParam("cname", qCname); err != nil {
				return err
			}
		}

	}

	if o.DNSZone != nil {

		// query param dnsZone
		var qrDNSZone string
		if o.DNSZone != nil {
			qrDNSZone = *o.DNSZone
		}
		qDNSZone := qrDNSZone
		if qDNSZone != "" {
			if err := r.SetQueryParam("dnsZone", qDNSZone); err != nil {
				return err
			}
		}

	}

	if o.Environment != nil {

		// query param environment
		var qrEnvironment string
		if o.Environment != nil {
			qrEnvironment = *o.Environment
		}
		qEnvironment := qrEnvironment
		if qEnvironment != "" {
			if err := r.SetQueryParam("environment", qEnvironment); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
