// Code generated by go-swagger; DO NOT EDIT.

package v1internaldistrox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewGetDistroXStatusInternalV1ByCrnsParams creates a new GetDistroXStatusInternalV1ByCrnsParams object
// with the default values initialized.
func NewGetDistroXStatusInternalV1ByCrnsParams() *GetDistroXStatusInternalV1ByCrnsParams {
	var ()
	return &GetDistroXStatusInternalV1ByCrnsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDistroXStatusInternalV1ByCrnsParamsWithTimeout creates a new GetDistroXStatusInternalV1ByCrnsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDistroXStatusInternalV1ByCrnsParamsWithTimeout(timeout time.Duration) *GetDistroXStatusInternalV1ByCrnsParams {
	var ()
	return &GetDistroXStatusInternalV1ByCrnsParams{

		timeout: timeout,
	}
}

// NewGetDistroXStatusInternalV1ByCrnsParamsWithContext creates a new GetDistroXStatusInternalV1ByCrnsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDistroXStatusInternalV1ByCrnsParamsWithContext(ctx context.Context) *GetDistroXStatusInternalV1ByCrnsParams {
	var ()
	return &GetDistroXStatusInternalV1ByCrnsParams{

		Context: ctx,
	}
}

// NewGetDistroXStatusInternalV1ByCrnsParamsWithHTTPClient creates a new GetDistroXStatusInternalV1ByCrnsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDistroXStatusInternalV1ByCrnsParamsWithHTTPClient(client *http.Client) *GetDistroXStatusInternalV1ByCrnsParams {
	var ()
	return &GetDistroXStatusInternalV1ByCrnsParams{
		HTTPClient: client,
	}
}

/*
GetDistroXStatusInternalV1ByCrnsParams contains all the parameters to send to the API endpoint
for the get distro x status internal v1 by crns operation typically these are written to a http.Request
*/
type GetDistroXStatusInternalV1ByCrnsParams struct {

	/*Body*/
	Body *model.StatusCrnsV4Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get distro x status internal v1 by crns params
func (o *GetDistroXStatusInternalV1ByCrnsParams) WithTimeout(timeout time.Duration) *GetDistroXStatusInternalV1ByCrnsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get distro x status internal v1 by crns params
func (o *GetDistroXStatusInternalV1ByCrnsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get distro x status internal v1 by crns params
func (o *GetDistroXStatusInternalV1ByCrnsParams) WithContext(ctx context.Context) *GetDistroXStatusInternalV1ByCrnsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get distro x status internal v1 by crns params
func (o *GetDistroXStatusInternalV1ByCrnsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get distro x status internal v1 by crns params
func (o *GetDistroXStatusInternalV1ByCrnsParams) WithHTTPClient(client *http.Client) *GetDistroXStatusInternalV1ByCrnsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get distro x status internal v1 by crns params
func (o *GetDistroXStatusInternalV1ByCrnsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get distro x status internal v1 by crns params
func (o *GetDistroXStatusInternalV1ByCrnsParams) WithBody(body *model.StatusCrnsV4Request) *GetDistroXStatusInternalV1ByCrnsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get distro x status internal v1 by crns params
func (o *GetDistroXStatusInternalV1ByCrnsParams) SetBody(body *model.StatusCrnsV4Request) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetDistroXStatusInternalV1ByCrnsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
