#!/bin/bash

CURRENT_VERSION=$(go version | awk 'NR==1{print $3}' | cut -c 3-)

SEPARATED=(${CURRENT_VERSION//./ })
EXPECTED_MINIMAL_MAJOR_VERSION=1
EXPECTED_MINIMAL_MINOR_VERSION=13

CURRENT_MAJOR_VERSION=$((SEPARATED[0]))
CURRENT_MINOR_VERSION=$((SEPARATED[1]))

if [ $CURRENT_MAJOR_VERSION -lt $EXPECTED_MINIMAL_MAJOR_VERSION ] || [ $CURRENT_MINOR_VERSION -lt $EXPECTED_MINIMAL_MINOR_VERSION ]; then
  echo "Your Go version is ($CURRENT_VERSION) lower than $EXPECTED_MINIMAL_MAJOR_VERSION.$EXPECTED_MINIMAL_MINOR_VERSION, please upgrade it!"
fi