// Code generated by go-swagger; DO NOT EDIT.

package v1platform_resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-environment/model"
)

// GetNoSQLTablesReader is a Reader for the GetNoSQLTables structure.
type GetNoSQLTablesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNoSQLTablesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNoSQLTablesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNoSQLTablesOK creates a GetNoSQLTablesOK with default headers values
func NewGetNoSQLTablesOK() *GetNoSQLTablesOK {
	return &GetNoSQLTablesOK{}
}

/*
GetNoSQLTablesOK handles this case with default header values.

successful operation
*/
type GetNoSQLTablesOK struct {
	Payload *model.PlatformNoSQLTablesResponse
}

func (o *GetNoSQLTablesOK) Error() string {
	return fmt.Sprintf("[GET /v1/platform_resources/nosql_tables][%d] getNoSqlTablesOK  %+v", 200, o.Payload)
}

func (o *GetNoSQLTablesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.PlatformNoSQLTablesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
