// Code generated by go-swagger; DO NOT EDIT.

package autoscale

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLimitsConfigurationParams creates a new GetLimitsConfigurationParams object
// with the default values initialized.
func NewGetLimitsConfigurationParams() *GetLimitsConfigurationParams {
	var ()
	return &GetLimitsConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLimitsConfigurationParamsWithTimeout creates a new GetLimitsConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLimitsConfigurationParamsWithTimeout(timeout time.Duration) *GetLimitsConfigurationParams {
	var ()
	return &GetLimitsConfigurationParams{

		timeout: timeout,
	}
}

// NewGetLimitsConfigurationParamsWithContext creates a new GetLimitsConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLimitsConfigurationParamsWithContext(ctx context.Context) *GetLimitsConfigurationParams {
	var ()
	return &GetLimitsConfigurationParams{

		Context: ctx,
	}
}

// NewGetLimitsConfigurationParamsWithHTTPClient creates a new GetLimitsConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLimitsConfigurationParamsWithHTTPClient(client *http.Client) *GetLimitsConfigurationParams {
	var ()
	return &GetLimitsConfigurationParams{
		HTTPClient: client,
	}
}

/*
GetLimitsConfigurationParams contains all the parameters to send to the API endpoint
for the get limits configuration operation typically these are written to a http.Request
*/
type GetLimitsConfigurationParams struct {

	/*AccountID*/
	AccountID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get limits configuration params
func (o *GetLimitsConfigurationParams) WithTimeout(timeout time.Duration) *GetLimitsConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get limits configuration params
func (o *GetLimitsConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get limits configuration params
func (o *GetLimitsConfigurationParams) WithContext(ctx context.Context) *GetLimitsConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get limits configuration params
func (o *GetLimitsConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get limits configuration params
func (o *GetLimitsConfigurationParams) WithHTTPClient(client *http.Client) *GetLimitsConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get limits configuration params
func (o *GetLimitsConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get limits configuration params
func (o *GetLimitsConfigurationParams) WithAccountID(accountID *string) *GetLimitsConfigurationParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get limits configuration params
func (o *GetLimitsConfigurationParams) SetAccountID(accountID *string) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetLimitsConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccountID != nil {

		// query param accountId
		var qrAccountID string
		if o.AccountID != nil {
			qrAccountID = *o.AccountID
		}
		qAccountID := qrAccountID
		if qAccountID != "" {
			if err := r.SetQueryParam("accountId", qAccountID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
