// Code generated by go-swagger; DO NOT EDIT.

package autoscale

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInternalAutoscaleClusterByNameParams creates a new GetInternalAutoscaleClusterByNameParams object
// with the default values initialized.
func NewGetInternalAutoscaleClusterByNameParams() *GetInternalAutoscaleClusterByNameParams {
	var ()
	return &GetInternalAutoscaleClusterByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInternalAutoscaleClusterByNameParamsWithTimeout creates a new GetInternalAutoscaleClusterByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInternalAutoscaleClusterByNameParamsWithTimeout(timeout time.Duration) *GetInternalAutoscaleClusterByNameParams {
	var ()
	return &GetInternalAutoscaleClusterByNameParams{

		timeout: timeout,
	}
}

// NewGetInternalAutoscaleClusterByNameParamsWithContext creates a new GetInternalAutoscaleClusterByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInternalAutoscaleClusterByNameParamsWithContext(ctx context.Context) *GetInternalAutoscaleClusterByNameParams {
	var ()
	return &GetInternalAutoscaleClusterByNameParams{

		Context: ctx,
	}
}

// NewGetInternalAutoscaleClusterByNameParamsWithHTTPClient creates a new GetInternalAutoscaleClusterByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInternalAutoscaleClusterByNameParamsWithHTTPClient(client *http.Client) *GetInternalAutoscaleClusterByNameParams {
	var ()
	return &GetInternalAutoscaleClusterByNameParams{
		HTTPClient: client,
	}
}

/*GetInternalAutoscaleClusterByNameParams contains all the parameters to send to the API endpoint
for the get internal autoscale cluster by name operation typically these are written to a http.Request
*/
type GetInternalAutoscaleClusterByNameParams struct {

	/*AccountID*/
	AccountID *string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) WithTimeout(timeout time.Duration) *GetInternalAutoscaleClusterByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) WithContext(ctx context.Context) *GetInternalAutoscaleClusterByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) WithHTTPClient(client *http.Client) *GetInternalAutoscaleClusterByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) WithAccountID(accountID *string) *GetInternalAutoscaleClusterByNameParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) SetAccountID(accountID *string) {
	o.AccountID = accountID
}

// WithName adds the name to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) WithName(name string) *GetInternalAutoscaleClusterByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get internal autoscale cluster by name params
func (o *GetInternalAutoscaleClusterByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetInternalAutoscaleClusterByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccountID != nil {

		// query param accountId
		var qrAccountID string
		if o.AccountID != nil {
			qrAccountID = *o.AccountID
		}
		qAccountID := qrAccountID
		if qAccountID != "" {
			if err := r.SetQueryParam("accountId", qAccountID); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
