// Code generated by go-swagger; DO NOT EDIT.

package autoscale

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewPutStackForAutoscaleStartByNameParams creates a new PutStackForAutoscaleStartByNameParams object
// with the default values initialized.
func NewPutStackForAutoscaleStartByNameParams() *PutStackForAutoscaleStartByNameParams {
	var ()
	return &PutStackForAutoscaleStartByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutStackForAutoscaleStartByNameParamsWithTimeout creates a new PutStackForAutoscaleStartByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutStackForAutoscaleStartByNameParamsWithTimeout(timeout time.Duration) *PutStackForAutoscaleStartByNameParams {
	var ()
	return &PutStackForAutoscaleStartByNameParams{

		timeout: timeout,
	}
}

// NewPutStackForAutoscaleStartByNameParamsWithContext creates a new PutStackForAutoscaleStartByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutStackForAutoscaleStartByNameParamsWithContext(ctx context.Context) *PutStackForAutoscaleStartByNameParams {
	var ()
	return &PutStackForAutoscaleStartByNameParams{

		Context: ctx,
	}
}

// NewPutStackForAutoscaleStartByNameParamsWithHTTPClient creates a new PutStackForAutoscaleStartByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutStackForAutoscaleStartByNameParamsWithHTTPClient(client *http.Client) *PutStackForAutoscaleStartByNameParams {
	var ()
	return &PutStackForAutoscaleStartByNameParams{
		HTTPClient: client,
	}
}

/*PutStackForAutoscaleStartByNameParams contains all the parameters to send to the API endpoint
for the put stack for autoscale start by name operation typically these are written to a http.Request
*/
type PutStackForAutoscaleStartByNameParams struct {

	/*Body*/
	Body *model.UpdateStackV4Request
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) WithTimeout(timeout time.Duration) *PutStackForAutoscaleStartByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) WithContext(ctx context.Context) *PutStackForAutoscaleStartByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) WithHTTPClient(client *http.Client) *PutStackForAutoscaleStartByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) WithBody(body *model.UpdateStackV4Request) *PutStackForAutoscaleStartByNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) SetBody(body *model.UpdateStackV4Request) {
	o.Body = body
}

// WithName adds the name to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) WithName(name string) *PutStackForAutoscaleStartByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put stack for autoscale start by name params
func (o *PutStackForAutoscaleStartByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PutStackForAutoscaleStartByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
