// Code generated by go-swagger; DO NOT EDIT.

package v1distrox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// CollectDistroxCmBasedDiagnosticsV1Reader is a Reader for the CollectDistroxCmBasedDiagnosticsV1 structure.
type CollectDistroxCmBasedDiagnosticsV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CollectDistroxCmBasedDiagnosticsV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCollectDistroxCmBasedDiagnosticsV1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCollectDistroxCmBasedDiagnosticsV1OK creates a CollectDistroxCmBasedDiagnosticsV1OK with default headers values
func NewCollectDistroxCmBasedDiagnosticsV1OK() *CollectDistroxCmBasedDiagnosticsV1OK {
	return &CollectDistroxCmBasedDiagnosticsV1OK{}
}

/*CollectDistroxCmBasedDiagnosticsV1OK handles this case with default header values.

successful operation
*/
type CollectDistroxCmBasedDiagnosticsV1OK struct {
	Payload *model.FlowIdentifier
}

func (o *CollectDistroxCmBasedDiagnosticsV1OK) Error() string {
	return fmt.Sprintf("[POST /v1/distrox/diagnostics/cm][%d] collectDistroxCmBasedDiagnosticsV1OK  %+v", 200, o.Payload)
}

func (o *CollectDistroxCmBasedDiagnosticsV1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.FlowIdentifier)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
