// Code generated by go-swagger; DO NOT EDIT.

package v1distrox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewPutVerticalScalingDistroXV1ByCrnParams creates a new PutVerticalScalingDistroXV1ByCrnParams object
// with the default values initialized.
func NewPutVerticalScalingDistroXV1ByCrnParams() *PutVerticalScalingDistroXV1ByCrnParams {
	var ()
	return &PutVerticalScalingDistroXV1ByCrnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutVerticalScalingDistroXV1ByCrnParamsWithTimeout creates a new PutVerticalScalingDistroXV1ByCrnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutVerticalScalingDistroXV1ByCrnParamsWithTimeout(timeout time.Duration) *PutVerticalScalingDistroXV1ByCrnParams {
	var ()
	return &PutVerticalScalingDistroXV1ByCrnParams{

		timeout: timeout,
	}
}

// NewPutVerticalScalingDistroXV1ByCrnParamsWithContext creates a new PutVerticalScalingDistroXV1ByCrnParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutVerticalScalingDistroXV1ByCrnParamsWithContext(ctx context.Context) *PutVerticalScalingDistroXV1ByCrnParams {
	var ()
	return &PutVerticalScalingDistroXV1ByCrnParams{

		Context: ctx,
	}
}

// NewPutVerticalScalingDistroXV1ByCrnParamsWithHTTPClient creates a new PutVerticalScalingDistroXV1ByCrnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutVerticalScalingDistroXV1ByCrnParamsWithHTTPClient(client *http.Client) *PutVerticalScalingDistroXV1ByCrnParams {
	var ()
	return &PutVerticalScalingDistroXV1ByCrnParams{
		HTTPClient: client,
	}
}

/*PutVerticalScalingDistroXV1ByCrnParams contains all the parameters to send to the API endpoint
for the put vertical scaling distro x v1 by crn operation typically these are written to a http.Request
*/
type PutVerticalScalingDistroXV1ByCrnParams struct {

	/*Body*/
	Body *model.DistroXVerticalScaleV1Request
	/*Crn*/
	Crn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) WithTimeout(timeout time.Duration) *PutVerticalScalingDistroXV1ByCrnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) WithContext(ctx context.Context) *PutVerticalScalingDistroXV1ByCrnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) WithHTTPClient(client *http.Client) *PutVerticalScalingDistroXV1ByCrnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) WithBody(body *model.DistroXVerticalScaleV1Request) *PutVerticalScalingDistroXV1ByCrnParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) SetBody(body *model.DistroXVerticalScaleV1Request) {
	o.Body = body
}

// WithCrn adds the crn to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) WithCrn(crn string) *PutVerticalScalingDistroXV1ByCrnParams {
	o.SetCrn(crn)
	return o
}

// SetCrn adds the crn to the put vertical scaling distro x v1 by crn params
func (o *PutVerticalScalingDistroXV1ByCrnParams) SetCrn(crn string) {
	o.Crn = crn
}

// WriteToRequest writes these params to a swagger request
func (o *PutVerticalScalingDistroXV1ByCrnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param crn
	if err := r.SetPathParam("crn", o.Crn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
