// Code generated by go-swagger; DO NOT EDIT.

package v1freeipacost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListFreeIpaCostV1Params creates a new ListFreeIpaCostV1Params object
// with the default values initialized.
func NewListFreeIpaCostV1Params() *ListFreeIpaCostV1Params {
	var ()
	return &ListFreeIpaCostV1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewListFreeIpaCostV1ParamsWithTimeout creates a new ListFreeIpaCostV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewListFreeIpaCostV1ParamsWithTimeout(timeout time.Duration) *ListFreeIpaCostV1Params {
	var ()
	return &ListFreeIpaCostV1Params{

		timeout: timeout,
	}
}

// NewListFreeIpaCostV1ParamsWithContext creates a new ListFreeIpaCostV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewListFreeIpaCostV1ParamsWithContext(ctx context.Context) *ListFreeIpaCostV1Params {
	var ()
	return &ListFreeIpaCostV1Params{

		Context: ctx,
	}
}

// NewListFreeIpaCostV1ParamsWithHTTPClient creates a new ListFreeIpaCostV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListFreeIpaCostV1ParamsWithHTTPClient(client *http.Client) *ListFreeIpaCostV1Params {
	var ()
	return &ListFreeIpaCostV1Params{
		HTTPClient: client,
	}
}

/*ListFreeIpaCostV1Params contains all the parameters to send to the API endpoint
for the list free ipa cost v1 operation typically these are written to a http.Request
*/
type ListFreeIpaCostV1Params struct {

	/*Body*/
	Body []string
	/*InitiatorUserCrn*/
	InitiatorUserCrn *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) WithTimeout(timeout time.Duration) *ListFreeIpaCostV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) WithContext(ctx context.Context) *ListFreeIpaCostV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) WithHTTPClient(client *http.Client) *ListFreeIpaCostV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) WithBody(body []string) *ListFreeIpaCostV1Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) SetBody(body []string) {
	o.Body = body
}

// WithInitiatorUserCrn adds the initiatorUserCrn to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) WithInitiatorUserCrn(initiatorUserCrn *string) *ListFreeIpaCostV1Params {
	o.SetInitiatorUserCrn(initiatorUserCrn)
	return o
}

// SetInitiatorUserCrn adds the initiatorUserCrn to the list free ipa cost v1 params
func (o *ListFreeIpaCostV1Params) SetInitiatorUserCrn(initiatorUserCrn *string) {
	o.InitiatorUserCrn = initiatorUserCrn
}

// WriteToRequest writes these params to a swagger request
func (o *ListFreeIpaCostV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.InitiatorUserCrn != nil {

		// query param initiatorUserCrn
		var qrInitiatorUserCrn string
		if o.InitiatorUserCrn != nil {
			qrInitiatorUserCrn = *o.InitiatorUserCrn
		}
		qInitiatorUserCrn := qrInitiatorUserCrn
		if qInitiatorUserCrn != "" {
			if err := r.SetQueryParam("initiatorUserCrn", qInitiatorUserCrn); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
