// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DatabaseAzureRequest database azure request
// swagger:model DatabaseAzureRequest
type DatabaseAzureRequest struct {

	// The type of the azure database: single server / flexible server
	// Enum: [SINGLE_SERVER FLEXIBLE_SERVER]
	AzureDatabaseType string `json:"azureDatabaseType,omitempty"`
}

// Validate validates this database azure request
func (m *DatabaseAzureRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAzureDatabaseType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var databaseAzureRequestTypeAzureDatabaseTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SINGLE_SERVER","FLEXIBLE_SERVER"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		databaseAzureRequestTypeAzureDatabaseTypePropEnum = append(databaseAzureRequestTypeAzureDatabaseTypePropEnum, v)
	}
}

const (

	// DatabaseAzureRequestAzureDatabaseTypeSINGLESERVER captures enum value "SINGLE_SERVER"
	DatabaseAzureRequestAzureDatabaseTypeSINGLESERVER string = "SINGLE_SERVER"

	// DatabaseAzureRequestAzureDatabaseTypeFLEXIBLESERVER captures enum value "FLEXIBLE_SERVER"
	DatabaseAzureRequestAzureDatabaseTypeFLEXIBLESERVER string = "FLEXIBLE_SERVER"
)

// prop value enum
func (m *DatabaseAzureRequest) validateAzureDatabaseTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, databaseAzureRequestTypeAzureDatabaseTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *DatabaseAzureRequest) validateAzureDatabaseType(formats strfmt.Registry) error {

	if swag.IsZero(m.AzureDatabaseType) { // not required
		return nil
	}

	// value enum
	if err := m.validateAzureDatabaseTypeEnum("azureDatabaseType", "body", m.AzureDatabaseType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DatabaseAzureRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatabaseAzureRequest) UnmarshalBinary(b []byte) error {
	var res DatabaseAzureRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
