// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Images images
// swagger:model Images
type Images struct {

	// base images
	// Read Only: true
	BaseImages []*Image `json:"base-images"`

	// cdh images
	// Read Only: true
	CdhImages []*Image `json:"cdh-images"`

	// freeipa images
	// Read Only: true
	FreeipaImages []*Image `json:"freeipa-images"`
}

// Validate validates this images
func (m *Images) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseImages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCdhImages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFreeipaImages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Images) validateBaseImages(formats strfmt.Registry) error {

	if swag.IsZero(m.BaseImages) { // not required
		return nil
	}

	for i := 0; i < len(m.BaseImages); i++ {
		if swag.IsZero(m.BaseImages[i]) { // not required
			continue
		}

		if m.BaseImages[i] != nil {
			if err := m.BaseImages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("base-images" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Images) validateCdhImages(formats strfmt.Registry) error {

	if swag.IsZero(m.CdhImages) { // not required
		return nil
	}

	for i := 0; i < len(m.CdhImages); i++ {
		if swag.IsZero(m.CdhImages[i]) { // not required
			continue
		}

		if m.CdhImages[i] != nil {
			if err := m.CdhImages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cdh-images" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Images) validateFreeipaImages(formats strfmt.Registry) error {

	if swag.IsZero(m.FreeipaImages) { // not required
		return nil
	}

	for i := 0; i < len(m.FreeipaImages); i++ {
		if swag.IsZero(m.FreeipaImages[i]) { // not required
			continue
		}

		if m.FreeipaImages[i] != nil {
			if err := m.FreeipaImages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("freeipa-images" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Images) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Images) UnmarshalBinary(b []byte) error {
	var res Images
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
