// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SdxSyncComponentVersionsFromCmResponse sdx sync component versions from cm response
// swagger:model SdxSyncComponentVersionsFromCmResponse
type SdxSyncComponentVersionsFromCmResponse struct {

	// The id of the flow or flow chain that was triggered as part of the process.
	FlowIdentifier *FlowIdentifier `json:"flowIdentifier,omitempty"`
}

// Validate validates this sdx sync component versions from cm response
func (m *SdxSyncComponentVersionsFromCmResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFlowIdentifier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SdxSyncComponentVersionsFromCmResponse) validateFlowIdentifier(formats strfmt.Registry) error {

	if swag.IsZero(m.FlowIdentifier) { // not required
		return nil
	}

	if m.FlowIdentifier != nil {
		if err := m.FlowIdentifier.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("flowIdentifier")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SdxSyncComponentVersionsFromCmResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SdxSyncComponentVersionsFromCmResponse) UnmarshalBinary(b []byte) error {
	var res SdxSyncComponentVersionsFromCmResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
