// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SdxRecipe sdx recipe
// swagger:model SdxRecipe
type SdxRecipe struct {

	// Host group name.
	HostGroup string `json:"hostGroup,omitempty"`

	// Recipe name.
	Name string `json:"name,omitempty"`
}

// Validate validates this sdx recipe
func (m *SdxRecipe) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SdxRecipe) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SdxRecipe) UnmarshalBinary(b []byte) error {
	var res SdxRecipe
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
