version: 2
jobs:

  integration-test:
    machine:
      services:
        - docker
    steps:
      - checkout    
      - run:
          name: Install make uuid 
          command: sudo apt-get install -y uuid-runtime make  
      - run: |
          make integration-test
      - store_test_results:
          path: tests/
      - store_artifacts:
          path: tests/aruba/test-result.html
      - store_artifacts:
          path: tests/aruba/allure/

workflows:
  version: 2
  test:
    jobs:
       - integration-test

