// Code generated by go-swagger; DO NOT EDIT.

package v1events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStructuredEventsZipInAccountParams creates a new GetStructuredEventsZipInAccountParams object
// with the default values initialized.
func NewGetStructuredEventsZipInAccountParams() *GetStructuredEventsZipInAccountParams {
	var ()
	return &GetStructuredEventsZipInAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStructuredEventsZipInAccountParamsWithTimeout creates a new GetStructuredEventsZipInAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStructuredEventsZipInAccountParamsWithTimeout(timeout time.Duration) *GetStructuredEventsZipInAccountParams {
	var ()
	return &GetStructuredEventsZipInAccountParams{

		timeout: timeout,
	}
}

// NewGetStructuredEventsZipInAccountParamsWithContext creates a new GetStructuredEventsZipInAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStructuredEventsZipInAccountParamsWithContext(ctx context.Context) *GetStructuredEventsZipInAccountParams {
	var ()
	return &GetStructuredEventsZipInAccountParams{

		Context: ctx,
	}
}

// NewGetStructuredEventsZipInAccountParamsWithHTTPClient creates a new GetStructuredEventsZipInAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStructuredEventsZipInAccountParamsWithHTTPClient(client *http.Client) *GetStructuredEventsZipInAccountParams {
	var ()
	return &GetStructuredEventsZipInAccountParams{
		HTTPClient: client,
	}
}

/*GetStructuredEventsZipInAccountParams contains all the parameters to send to the API endpoint
for the get structured events zip in account operation typically these are written to a http.Request
*/
type GetStructuredEventsZipInAccountParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get structured events zip in account params
func (o *GetStructuredEventsZipInAccountParams) WithTimeout(timeout time.Duration) *GetStructuredEventsZipInAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get structured events zip in account params
func (o *GetStructuredEventsZipInAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get structured events zip in account params
func (o *GetStructuredEventsZipInAccountParams) WithContext(ctx context.Context) *GetStructuredEventsZipInAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get structured events zip in account params
func (o *GetStructuredEventsZipInAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get structured events zip in account params
func (o *GetStructuredEventsZipInAccountParams) WithHTTPClient(client *http.Client) *GetStructuredEventsZipInAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get structured events zip in account params
func (o *GetStructuredEventsZipInAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get structured events zip in account params
func (o *GetStructuredEventsZipInAccountParams) WithName(name string) *GetStructuredEventsZipInAccountParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get structured events zip in account params
func (o *GetStructuredEventsZipInAccountParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetStructuredEventsZipInAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
