// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_blueprints_util

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateRecommendationForWorkspaceByEnvCrnParams creates a new CreateRecommendationForWorkspaceByEnvCrnParams object
// with the default values initialized.
func NewCreateRecommendationForWorkspaceByEnvCrnParams() *CreateRecommendationForWorkspaceByEnvCrnParams {
	var ()
	return &CreateRecommendationForWorkspaceByEnvCrnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRecommendationForWorkspaceByEnvCrnParamsWithTimeout creates a new CreateRecommendationForWorkspaceByEnvCrnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRecommendationForWorkspaceByEnvCrnParamsWithTimeout(timeout time.Duration) *CreateRecommendationForWorkspaceByEnvCrnParams {
	var ()
	return &CreateRecommendationForWorkspaceByEnvCrnParams{

		timeout: timeout,
	}
}

// NewCreateRecommendationForWorkspaceByEnvCrnParamsWithContext creates a new CreateRecommendationForWorkspaceByEnvCrnParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRecommendationForWorkspaceByEnvCrnParamsWithContext(ctx context.Context) *CreateRecommendationForWorkspaceByEnvCrnParams {
	var ()
	return &CreateRecommendationForWorkspaceByEnvCrnParams{

		Context: ctx,
	}
}

// NewCreateRecommendationForWorkspaceByEnvCrnParamsWithHTTPClient creates a new CreateRecommendationForWorkspaceByEnvCrnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRecommendationForWorkspaceByEnvCrnParamsWithHTTPClient(client *http.Client) *CreateRecommendationForWorkspaceByEnvCrnParams {
	var ()
	return &CreateRecommendationForWorkspaceByEnvCrnParams{
		HTTPClient: client,
	}
}

/*CreateRecommendationForWorkspaceByEnvCrnParams contains all the parameters to send to the API endpoint
for the create recommendation for workspace by env crn operation typically these are written to a http.Request
*/
type CreateRecommendationForWorkspaceByEnvCrnParams struct {

	/*AvailabilityZone*/
	AvailabilityZone *string
	/*BlueprintName*/
	BlueprintName *string
	/*EnvironmentCrn*/
	EnvironmentCrn *string
	/*PlatformVariant*/
	PlatformVariant *string
	/*Region*/
	Region *string
	/*ResourceType*/
	ResourceType *string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithTimeout(timeout time.Duration) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithContext(ctx context.Context) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithHTTPClient(client *http.Client) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAvailabilityZone adds the availabilityZone to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithAvailabilityZone(availabilityZone *string) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetAvailabilityZone(availabilityZone)
	return o
}

// SetAvailabilityZone adds the availabilityZone to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetAvailabilityZone(availabilityZone *string) {
	o.AvailabilityZone = availabilityZone
}

// WithBlueprintName adds the blueprintName to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithBlueprintName(blueprintName *string) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetBlueprintName(blueprintName)
	return o
}

// SetBlueprintName adds the blueprintName to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetBlueprintName(blueprintName *string) {
	o.BlueprintName = blueprintName
}

// WithEnvironmentCrn adds the environmentCrn to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithEnvironmentCrn(environmentCrn *string) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetEnvironmentCrn(environmentCrn)
	return o
}

// SetEnvironmentCrn adds the environmentCrn to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetEnvironmentCrn(environmentCrn *string) {
	o.EnvironmentCrn = environmentCrn
}

// WithPlatformVariant adds the platformVariant to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithPlatformVariant(platformVariant *string) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetPlatformVariant(platformVariant)
	return o
}

// SetPlatformVariant adds the platformVariant to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetPlatformVariant(platformVariant *string) {
	o.PlatformVariant = platformVariant
}

// WithRegion adds the region to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithRegion(region *string) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetRegion(region *string) {
	o.Region = region
}

// WithResourceType adds the resourceType to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithResourceType(resourceType *string) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetResourceType(resourceType)
	return o
}

// SetResourceType adds the resourceType to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetResourceType(resourceType *string) {
	o.ResourceType = resourceType
}

// WithWorkspaceID adds the workspaceID to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WithWorkspaceID(workspaceID int64) *CreateRecommendationForWorkspaceByEnvCrnParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the create recommendation for workspace by env crn params
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRecommendationForWorkspaceByEnvCrnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AvailabilityZone != nil {

		// query param availabilityZone
		var qrAvailabilityZone string
		if o.AvailabilityZone != nil {
			qrAvailabilityZone = *o.AvailabilityZone
		}
		qAvailabilityZone := qrAvailabilityZone
		if qAvailabilityZone != "" {
			if err := r.SetQueryParam("availabilityZone", qAvailabilityZone); err != nil {
				return err
			}
		}

	}

	if o.BlueprintName != nil {

		// query param blueprintName
		var qrBlueprintName string
		if o.BlueprintName != nil {
			qrBlueprintName = *o.BlueprintName
		}
		qBlueprintName := qrBlueprintName
		if qBlueprintName != "" {
			if err := r.SetQueryParam("blueprintName", qBlueprintName); err != nil {
				return err
			}
		}

	}

	if o.EnvironmentCrn != nil {

		// query param environmentCrn
		var qrEnvironmentCrn string
		if o.EnvironmentCrn != nil {
			qrEnvironmentCrn = *o.EnvironmentCrn
		}
		qEnvironmentCrn := qrEnvironmentCrn
		if qEnvironmentCrn != "" {
			if err := r.SetQueryParam("environmentCrn", qEnvironmentCrn); err != nil {
				return err
			}
		}

	}

	if o.PlatformVariant != nil {

		// query param platformVariant
		var qrPlatformVariant string
		if o.PlatformVariant != nil {
			qrPlatformVariant = *o.PlatformVariant
		}
		qPlatformVariant := qrPlatformVariant
		if qPlatformVariant != "" {
			if err := r.SetQueryParam("platformVariant", qPlatformVariant); err != nil {
				return err
			}
		}

	}

	if o.Region != nil {

		// query param region
		var qrRegion string
		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {
			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}

	}

	if o.ResourceType != nil {

		// query param resourceType
		var qrResourceType string
		if o.ResourceType != nil {
			qrResourceType = *o.ResourceType
		}
		qResourceType := qrResourceType
		if qResourceType != "" {
			if err := r.SetQueryParam("resourceType", qResourceType); err != nil {
				return err
			}
		}

	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
