// Code generated by go-swagger; DO NOT EDIT.

package v4custom_configurations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewPostParams creates a new PostParams object
// with the default values initialized.
func NewPostParams() *PostParams {
	var ()
	return &PostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostParamsWithTimeout creates a new PostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostParamsWithTimeout(timeout time.Duration) *PostParams {
	var ()
	return &PostParams{

		timeout: timeout,
	}
}

// NewPostParamsWithContext creates a new PostParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostParamsWithContext(ctx context.Context) *PostParams {
	var ()
	return &PostParams{

		Context: ctx,
	}
}

// NewPostParamsWithHTTPClient creates a new PostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostParamsWithHTTPClient(client *http.Client) *PostParams {
	var ()
	return &PostParams{
		HTTPClient: client,
	}
}

/*
PostParams contains all the parameters to send to the API endpoint
for the post operation typically these are written to a http.Request
*/
type PostParams struct {

	/*Body*/
	Body *model.CustomConfigurationsV4Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post params
func (o *PostParams) WithTimeout(timeout time.Duration) *PostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post params
func (o *PostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post params
func (o *PostParams) WithContext(ctx context.Context) *PostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post params
func (o *PostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post params
func (o *PostParams) WithHTTPClient(client *http.Client) *PostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post params
func (o *PostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post params
func (o *PostParams) WithBody(body *model.CustomConfigurationsV4Request) *PostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post params
func (o *PostParams) SetBody(body *model.CustomConfigurationsV4Request) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
