// Code generated by go-swagger; DO NOT EDIT.

package v1env

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteEnvironmentsByNameParams creates a new DeleteEnvironmentsByNameParams object
// with the default values initialized.
func NewDeleteEnvironmentsByNameParams() *DeleteEnvironmentsByNameParams {
	var (
		cascadingDefault = bool(false)
		forcedDefault    = bool(false)
	)
	return &DeleteEnvironmentsByNameParams{
		Cascading: &cascadingDefault,
		Forced:    &forcedDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEnvironmentsByNameParamsWithTimeout creates a new DeleteEnvironmentsByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteEnvironmentsByNameParamsWithTimeout(timeout time.Duration) *DeleteEnvironmentsByNameParams {
	var (
		cascadingDefault = bool(false)
		forcedDefault    = bool(false)
	)
	return &DeleteEnvironmentsByNameParams{
		Cascading: &cascadingDefault,
		Forced:    &forcedDefault,

		timeout: timeout,
	}
}

// NewDeleteEnvironmentsByNameParamsWithContext creates a new DeleteEnvironmentsByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteEnvironmentsByNameParamsWithContext(ctx context.Context) *DeleteEnvironmentsByNameParams {
	var (
		cascadingDefault = bool(false)
		forcedDefault    = bool(false)
	)
	return &DeleteEnvironmentsByNameParams{
		Cascading: &cascadingDefault,
		Forced:    &forcedDefault,

		Context: ctx,
	}
}

// NewDeleteEnvironmentsByNameParamsWithHTTPClient creates a new DeleteEnvironmentsByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteEnvironmentsByNameParamsWithHTTPClient(client *http.Client) *DeleteEnvironmentsByNameParams {
	var (
		cascadingDefault = bool(false)
		forcedDefault    = bool(false)
	)
	return &DeleteEnvironmentsByNameParams{
		Cascading:  &cascadingDefault,
		Forced:     &forcedDefault,
		HTTPClient: client,
	}
}

/*DeleteEnvironmentsByNameParams contains all the parameters to send to the API endpoint
for the delete environments by name operation typically these are written to a http.Request
*/
type DeleteEnvironmentsByNameParams struct {

	/*Body*/
	Body []string
	/*Cascading*/
	Cascading *bool
	/*Forced*/
	Forced *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) WithTimeout(timeout time.Duration) *DeleteEnvironmentsByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) WithContext(ctx context.Context) *DeleteEnvironmentsByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) WithHTTPClient(client *http.Client) *DeleteEnvironmentsByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) WithBody(body []string) *DeleteEnvironmentsByNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) SetBody(body []string) {
	o.Body = body
}

// WithCascading adds the cascading to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) WithCascading(cascading *bool) *DeleteEnvironmentsByNameParams {
	o.SetCascading(cascading)
	return o
}

// SetCascading adds the cascading to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) SetCascading(cascading *bool) {
	o.Cascading = cascading
}

// WithForced adds the forced to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) WithForced(forced *bool) *DeleteEnvironmentsByNameParams {
	o.SetForced(forced)
	return o
}

// SetForced adds the forced to the delete environments by name params
func (o *DeleteEnvironmentsByNameParams) SetForced(forced *bool) {
	o.Forced = forced
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEnvironmentsByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Cascading != nil {

		// query param cascading
		var qrCascading bool
		if o.Cascading != nil {
			qrCascading = *o.Cascading
		}
		qCascading := swag.FormatBool(qrCascading)
		if qCascading != "" {
			if err := r.SetQueryParam("cascading", qCascading); err != nil {
				return err
			}
		}

	}

	if o.Forced != nil {

		// query param forced
		var qrForced bool
		if o.Forced != nil {
			qrForced = *o.Forced
		}
		qForced := swag.FormatBool(qrForced)
		if qForced != "" {
			if err := r.SetQueryParam("forced", qForced); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
