// Code generated by go-swagger; DO NOT EDIT.

package v1env

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEnvironmentFlowLogsProgressByResourceCrnParams creates a new GetEnvironmentFlowLogsProgressByResourceCrnParams object
// with the default values initialized.
func NewGetEnvironmentFlowLogsProgressByResourceCrnParams() *GetEnvironmentFlowLogsProgressByResourceCrnParams {
	var ()
	return &GetEnvironmentFlowLogsProgressByResourceCrnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEnvironmentFlowLogsProgressByResourceCrnParamsWithTimeout creates a new GetEnvironmentFlowLogsProgressByResourceCrnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEnvironmentFlowLogsProgressByResourceCrnParamsWithTimeout(timeout time.Duration) *GetEnvironmentFlowLogsProgressByResourceCrnParams {
	var ()
	return &GetEnvironmentFlowLogsProgressByResourceCrnParams{

		timeout: timeout,
	}
}

// NewGetEnvironmentFlowLogsProgressByResourceCrnParamsWithContext creates a new GetEnvironmentFlowLogsProgressByResourceCrnParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEnvironmentFlowLogsProgressByResourceCrnParamsWithContext(ctx context.Context) *GetEnvironmentFlowLogsProgressByResourceCrnParams {
	var ()
	return &GetEnvironmentFlowLogsProgressByResourceCrnParams{

		Context: ctx,
	}
}

// NewGetEnvironmentFlowLogsProgressByResourceCrnParamsWithHTTPClient creates a new GetEnvironmentFlowLogsProgressByResourceCrnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEnvironmentFlowLogsProgressByResourceCrnParamsWithHTTPClient(client *http.Client) *GetEnvironmentFlowLogsProgressByResourceCrnParams {
	var ()
	return &GetEnvironmentFlowLogsProgressByResourceCrnParams{
		HTTPClient: client,
	}
}

/*GetEnvironmentFlowLogsProgressByResourceCrnParams contains all the parameters to send to the API endpoint
for the get environment flow logs progress by resource crn operation typically these are written to a http.Request
*/
type GetEnvironmentFlowLogsProgressByResourceCrnParams struct {

	/*ResourceCrn*/
	ResourceCrn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get environment flow logs progress by resource crn params
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) WithTimeout(timeout time.Duration) *GetEnvironmentFlowLogsProgressByResourceCrnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get environment flow logs progress by resource crn params
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get environment flow logs progress by resource crn params
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) WithContext(ctx context.Context) *GetEnvironmentFlowLogsProgressByResourceCrnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get environment flow logs progress by resource crn params
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get environment flow logs progress by resource crn params
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) WithHTTPClient(client *http.Client) *GetEnvironmentFlowLogsProgressByResourceCrnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get environment flow logs progress by resource crn params
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceCrn adds the resourceCrn to the get environment flow logs progress by resource crn params
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) WithResourceCrn(resourceCrn string) *GetEnvironmentFlowLogsProgressByResourceCrnParams {
	o.SetResourceCrn(resourceCrn)
	return o
}

// SetResourceCrn adds the resourceCrn to the get environment flow logs progress by resource crn params
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) SetResourceCrn(resourceCrn string) {
	o.ResourceCrn = resourceCrn
}

// WriteToRequest writes these params to a swagger request
func (o *GetEnvironmentFlowLogsProgressByResourceCrnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceCrn
	if err := r.SetPathParam("resourceCrn", o.ResourceCrn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
