// Code generated by go-swagger; DO NOT EDIT.

package v1env

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCreateEnvironmentForCliByCrnReader is a Reader for the GetCreateEnvironmentForCliByCrn structure.
type GetCreateEnvironmentForCliByCrnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCreateEnvironmentForCliByCrnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCreateEnvironmentForCliByCrnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCreateEnvironmentForCliByCrnOK creates a GetCreateEnvironmentForCliByCrnOK with default headers values
func NewGetCreateEnvironmentForCliByCrnOK() *GetCreateEnvironmentForCliByCrnOK {
	return &GetCreateEnvironmentForCliByCrnOK{}
}

/*GetCreateEnvironmentForCliByCrnOK handles this case with default header values.

successful operation
*/
type GetCreateEnvironmentForCliByCrnOK struct {
	Payload interface{}
}

func (o *GetCreateEnvironmentForCliByCrnOK) Error() string {
	return fmt.Sprintf("[POST /v1/env/crn/{crn}/cli_create][%d] getCreateEnvironmentForCliByCrnOK  %+v", 200, o.Payload)
}

func (o *GetCreateEnvironmentForCliByCrnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
