// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UpgradeV4Request upgrade v4 request
// swagger:model UpgradeV4Request
type UpgradeV4Request struct {

	// Checks the eligibility of an image to upgrade
	DryRun bool `json:"dryRun,omitempty"`

	// empty
	Empty bool `json:"empty,omitempty"`

	// UUID of the image to upgrade
	ImageID string `json:"imageId,omitempty"`

	// Upgrades to image with the same version of stack and clustermanager, if available
	LockComponents bool `json:"lockComponents,omitempty"`

	// Cloudera Runtime version
	Runtime string `json:"runtime,omitempty"`
}

// Validate validates this upgrade v4 request
func (m *UpgradeV4Request) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpgradeV4Request) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpgradeV4Request) UnmarshalBinary(b []byte) error {
	var res UpgradeV4Request
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
