// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStackByCrnInWorkspaceV4Params creates a new GetStackByCrnInWorkspaceV4Params object
// with the default values initialized.
func NewGetStackByCrnInWorkspaceV4Params() *GetStackByCrnInWorkspaceV4Params {
	var ()
	return &GetStackByCrnInWorkspaceV4Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStackByCrnInWorkspaceV4ParamsWithTimeout creates a new GetStackByCrnInWorkspaceV4Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStackByCrnInWorkspaceV4ParamsWithTimeout(timeout time.Duration) *GetStackByCrnInWorkspaceV4Params {
	var ()
	return &GetStackByCrnInWorkspaceV4Params{

		timeout: timeout,
	}
}

// NewGetStackByCrnInWorkspaceV4ParamsWithContext creates a new GetStackByCrnInWorkspaceV4Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetStackByCrnInWorkspaceV4ParamsWithContext(ctx context.Context) *GetStackByCrnInWorkspaceV4Params {
	var ()
	return &GetStackByCrnInWorkspaceV4Params{

		Context: ctx,
	}
}

// NewGetStackByCrnInWorkspaceV4ParamsWithHTTPClient creates a new GetStackByCrnInWorkspaceV4Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStackByCrnInWorkspaceV4ParamsWithHTTPClient(client *http.Client) *GetStackByCrnInWorkspaceV4Params {
	var ()
	return &GetStackByCrnInWorkspaceV4Params{
		HTTPClient: client,
	}
}

/*GetStackByCrnInWorkspaceV4Params contains all the parameters to send to the API endpoint
for the get stack by crn in workspace v4 operation typically these are written to a http.Request
*/
type GetStackByCrnInWorkspaceV4Params struct {

	/*Crn*/
	Crn string
	/*Entries*/
	Entries []string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) WithTimeout(timeout time.Duration) *GetStackByCrnInWorkspaceV4Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) WithContext(ctx context.Context) *GetStackByCrnInWorkspaceV4Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) WithHTTPClient(client *http.Client) *GetStackByCrnInWorkspaceV4Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCrn adds the crn to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) WithCrn(crn string) *GetStackByCrnInWorkspaceV4Params {
	o.SetCrn(crn)
	return o
}

// SetCrn adds the crn to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) SetCrn(crn string) {
	o.Crn = crn
}

// WithEntries adds the entries to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) WithEntries(entries []string) *GetStackByCrnInWorkspaceV4Params {
	o.SetEntries(entries)
	return o
}

// SetEntries adds the entries to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) SetEntries(entries []string) {
	o.Entries = entries
}

// WithWorkspaceID adds the workspaceID to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) WithWorkspaceID(workspaceID int64) *GetStackByCrnInWorkspaceV4Params {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the get stack by crn in workspace v4 params
func (o *GetStackByCrnInWorkspaceV4Params) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetStackByCrnInWorkspaceV4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param crn
	if err := r.SetPathParam("crn", o.Crn); err != nil {
		return err
	}

	valuesEntries := o.Entries

	joinedEntries := swag.JoinByFormat(valuesEntries, "multi")
	// query array param entries
	if err := r.SetQueryParam("entries", joinedEntries...); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
