// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewRefreshRecipesInternalParams creates a new RefreshRecipesInternalParams object
// with the default values initialized.
func NewRefreshRecipesInternalParams() *RefreshRecipesInternalParams {
	var ()
	return &RefreshRecipesInternalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRefreshRecipesInternalParamsWithTimeout creates a new RefreshRecipesInternalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRefreshRecipesInternalParamsWithTimeout(timeout time.Duration) *RefreshRecipesInternalParams {
	var ()
	return &RefreshRecipesInternalParams{

		timeout: timeout,
	}
}

// NewRefreshRecipesInternalParamsWithContext creates a new RefreshRecipesInternalParams object
// with the default values initialized, and the ability to set a context for a request
func NewRefreshRecipesInternalParamsWithContext(ctx context.Context) *RefreshRecipesInternalParams {
	var ()
	return &RefreshRecipesInternalParams{

		Context: ctx,
	}
}

// NewRefreshRecipesInternalParamsWithHTTPClient creates a new RefreshRecipesInternalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRefreshRecipesInternalParamsWithHTTPClient(client *http.Client) *RefreshRecipesInternalParams {
	var ()
	return &RefreshRecipesInternalParams{
		HTTPClient: client,
	}
}

/*
RefreshRecipesInternalParams contains all the parameters to send to the API endpoint
for the refresh recipes internal operation typically these are written to a http.Request
*/
type RefreshRecipesInternalParams struct {

	/*Body*/
	Body *model.UpdateRecipesV4Request
	/*InitiatorUserCrn*/
	InitiatorUserCrn *string
	/*Name*/
	Name string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) WithTimeout(timeout time.Duration) *RefreshRecipesInternalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) WithContext(ctx context.Context) *RefreshRecipesInternalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) WithHTTPClient(client *http.Client) *RefreshRecipesInternalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) WithBody(body *model.UpdateRecipesV4Request) *RefreshRecipesInternalParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) SetBody(body *model.UpdateRecipesV4Request) {
	o.Body = body
}

// WithInitiatorUserCrn adds the initiatorUserCrn to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) WithInitiatorUserCrn(initiatorUserCrn *string) *RefreshRecipesInternalParams {
	o.SetInitiatorUserCrn(initiatorUserCrn)
	return o
}

// SetInitiatorUserCrn adds the initiatorUserCrn to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) SetInitiatorUserCrn(initiatorUserCrn *string) {
	o.InitiatorUserCrn = initiatorUserCrn
}

// WithName adds the name to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) WithName(name string) *RefreshRecipesInternalParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) SetName(name string) {
	o.Name = name
}

// WithWorkspaceID adds the workspaceID to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) WithWorkspaceID(workspaceID int64) *RefreshRecipesInternalParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the refresh recipes internal params
func (o *RefreshRecipesInternalParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *RefreshRecipesInternalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.InitiatorUserCrn != nil {

		// query param initiatorUserCrn
		var qrInitiatorUserCrn string
		if o.InitiatorUserCrn != nil {
			qrInitiatorUserCrn = *o.InitiatorUserCrn
		}
		qInitiatorUserCrn := qrInitiatorUserCrn
		if qInitiatorUserCrn != "" {
			if err := r.SetQueryParam("initiatorUserCrn", qInitiatorUserCrn); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
