// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// RenewStackCertificateReader is a Reader for the RenewStackCertificate structure.
type RenewStackCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RenewStackCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRenewStackCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRenewStackCertificateOK creates a RenewStackCertificateOK with default headers values
func NewRenewStackCertificateOK() *RenewStackCertificateOK {
	return &RenewStackCertificateOK{}
}

/*
RenewStackCertificateOK handles this case with default header values.

successful operation
*/
type RenewStackCertificateOK struct {
	Payload *model.FlowIdentifier
}

func (o *RenewStackCertificateOK) Error() string {
	return fmt.Sprintf("[POST /v4/{workspaceId}/stacks/internal/{name}/renew_certificate][%d] renewStackCertificateOK  %+v", 200, o.Payload)
}

func (o *RenewStackCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.FlowIdentifier)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
