// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// StopStackInWorkspaceV4InternalReader is a Reader for the StopStackInWorkspaceV4Internal structure.
type StopStackInWorkspaceV4InternalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StopStackInWorkspaceV4InternalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStopStackInWorkspaceV4InternalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStopStackInWorkspaceV4InternalOK creates a StopStackInWorkspaceV4InternalOK with default headers values
func NewStopStackInWorkspaceV4InternalOK() *StopStackInWorkspaceV4InternalOK {
	return &StopStackInWorkspaceV4InternalOK{}
}

/*StopStackInWorkspaceV4InternalOK handles this case with default header values.

successful operation
*/
type StopStackInWorkspaceV4InternalOK struct {
	Payload *model.FlowIdentifier
}

func (o *StopStackInWorkspaceV4InternalOK) Error() string {
	return fmt.Sprintf("[PUT /v4/{workspaceId}/stacks/internal/{name}/stop][%d] stopStackInWorkspaceV4InternalOK  %+v", 200, o.Payload)
}

func (o *StopStackInWorkspaceV4InternalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.FlowIdentifier)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
