// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api/model"
)

// NewSyncCmInWorkspaceV4Params creates a new SyncCmInWorkspaceV4Params object
// with the default values initialized.
func NewSyncCmInWorkspaceV4Params() *SyncCmInWorkspaceV4Params {
	var ()
	return &SyncCmInWorkspaceV4Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewSyncCmInWorkspaceV4ParamsWithTimeout creates a new SyncCmInWorkspaceV4Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewSyncCmInWorkspaceV4ParamsWithTimeout(timeout time.Duration) *SyncCmInWorkspaceV4Params {
	var ()
	return &SyncCmInWorkspaceV4Params{

		timeout: timeout,
	}
}

// NewSyncCmInWorkspaceV4ParamsWithContext creates a new SyncCmInWorkspaceV4Params object
// with the default values initialized, and the ability to set a context for a request
func NewSyncCmInWorkspaceV4ParamsWithContext(ctx context.Context) *SyncCmInWorkspaceV4Params {
	var ()
	return &SyncCmInWorkspaceV4Params{

		Context: ctx,
	}
}

// NewSyncCmInWorkspaceV4ParamsWithHTTPClient creates a new SyncCmInWorkspaceV4Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSyncCmInWorkspaceV4ParamsWithHTTPClient(client *http.Client) *SyncCmInWorkspaceV4Params {
	var ()
	return &SyncCmInWorkspaceV4Params{
		HTTPClient: client,
	}
}

/*SyncCmInWorkspaceV4Params contains all the parameters to send to the API endpoint
for the sync cm in workspace v4 operation typically these are written to a http.Request
*/
type SyncCmInWorkspaceV4Params struct {

	/*Body*/
	Body *model.ClouderaManagerSyncV4Request
	/*InitiatorUserCrn*/
	InitiatorUserCrn *string
	/*Name*/
	Name string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) WithTimeout(timeout time.Duration) *SyncCmInWorkspaceV4Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) WithContext(ctx context.Context) *SyncCmInWorkspaceV4Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) WithHTTPClient(client *http.Client) *SyncCmInWorkspaceV4Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) WithBody(body *model.ClouderaManagerSyncV4Request) *SyncCmInWorkspaceV4Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) SetBody(body *model.ClouderaManagerSyncV4Request) {
	o.Body = body
}

// WithInitiatorUserCrn adds the initiatorUserCrn to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) WithInitiatorUserCrn(initiatorUserCrn *string) *SyncCmInWorkspaceV4Params {
	o.SetInitiatorUserCrn(initiatorUserCrn)
	return o
}

// SetInitiatorUserCrn adds the initiatorUserCrn to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) SetInitiatorUserCrn(initiatorUserCrn *string) {
	o.InitiatorUserCrn = initiatorUserCrn
}

// WithName adds the name to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) WithName(name string) *SyncCmInWorkspaceV4Params {
	o.SetName(name)
	return o
}

// SetName adds the name to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) SetName(name string) {
	o.Name = name
}

// WithWorkspaceID adds the workspaceID to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) WithWorkspaceID(workspaceID int64) *SyncCmInWorkspaceV4Params {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the sync cm in workspace v4 params
func (o *SyncCmInWorkspaceV4Params) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *SyncCmInWorkspaceV4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.InitiatorUserCrn != nil {

		// query param initiatorUserCrn
		var qrInitiatorUserCrn string
		if o.InitiatorUserCrn != nil {
			qrInitiatorUserCrn = *o.InitiatorUserCrn
		}
		qInitiatorUserCrn := qrInitiatorUserCrn
		if qInitiatorUserCrn != "" {
			if err := r.SetQueryParam("initiatorUserCrn", qInitiatorUserCrn); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
