// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateSaltByNameParams creates a new UpdateSaltByNameParams object
// with the default values initialized.
func NewUpdateSaltByNameParams() *UpdateSaltByNameParams {
	var ()
	return &UpdateSaltByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSaltByNameParamsWithTimeout creates a new UpdateSaltByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateSaltByNameParamsWithTimeout(timeout time.Duration) *UpdateSaltByNameParams {
	var ()
	return &UpdateSaltByNameParams{

		timeout: timeout,
	}
}

// NewUpdateSaltByNameParamsWithContext creates a new UpdateSaltByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateSaltByNameParamsWithContext(ctx context.Context) *UpdateSaltByNameParams {
	var ()
	return &UpdateSaltByNameParams{

		Context: ctx,
	}
}

// NewUpdateSaltByNameParamsWithHTTPClient creates a new UpdateSaltByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateSaltByNameParamsWithHTTPClient(client *http.Client) *UpdateSaltByNameParams {
	var ()
	return &UpdateSaltByNameParams{
		HTTPClient: client,
	}
}

/*UpdateSaltByNameParams contains all the parameters to send to the API endpoint
for the update salt by name operation typically these are written to a http.Request
*/
type UpdateSaltByNameParams struct {

	/*Name*/
	Name string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update salt by name params
func (o *UpdateSaltByNameParams) WithTimeout(timeout time.Duration) *UpdateSaltByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update salt by name params
func (o *UpdateSaltByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update salt by name params
func (o *UpdateSaltByNameParams) WithContext(ctx context.Context) *UpdateSaltByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update salt by name params
func (o *UpdateSaltByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update salt by name params
func (o *UpdateSaltByNameParams) WithHTTPClient(client *http.Client) *UpdateSaltByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update salt by name params
func (o *UpdateSaltByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the update salt by name params
func (o *UpdateSaltByNameParams) WithName(name string) *UpdateSaltByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update salt by name params
func (o *UpdateSaltByNameParams) SetName(name string) {
	o.Name = name
}

// WithWorkspaceID adds the workspaceID to the update salt by name params
func (o *UpdateSaltByNameParams) WithWorkspaceID(workspaceID int64) *UpdateSaltByNameParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the update salt by name params
func (o *UpdateSaltByNameParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSaltByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
