// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-sdx/model"
)

// NewBackupDatabaseInternalParams creates a new BackupDatabaseInternalParams object
// with the default values initialized.
func NewBackupDatabaseInternalParams() *BackupDatabaseInternalParams {
	var ()
	return &BackupDatabaseInternalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBackupDatabaseInternalParamsWithTimeout creates a new BackupDatabaseInternalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBackupDatabaseInternalParamsWithTimeout(timeout time.Duration) *BackupDatabaseInternalParams {
	var ()
	return &BackupDatabaseInternalParams{

		timeout: timeout,
	}
}

// NewBackupDatabaseInternalParamsWithContext creates a new BackupDatabaseInternalParams object
// with the default values initialized, and the ability to set a context for a request
func NewBackupDatabaseInternalParamsWithContext(ctx context.Context) *BackupDatabaseInternalParams {
	var ()
	return &BackupDatabaseInternalParams{

		Context: ctx,
	}
}

// NewBackupDatabaseInternalParamsWithHTTPClient creates a new BackupDatabaseInternalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBackupDatabaseInternalParamsWithHTTPClient(client *http.Client) *BackupDatabaseInternalParams {
	var ()
	return &BackupDatabaseInternalParams{
		HTTPClient: client,
	}
}

/*
BackupDatabaseInternalParams contains all the parameters to send to the API endpoint
for the backup database internal operation typically these are written to a http.Request
*/
type BackupDatabaseInternalParams struct {

	/*Body*/
	Body *model.SdxDatabaseBackupRequest
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the backup database internal params
func (o *BackupDatabaseInternalParams) WithTimeout(timeout time.Duration) *BackupDatabaseInternalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the backup database internal params
func (o *BackupDatabaseInternalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the backup database internal params
func (o *BackupDatabaseInternalParams) WithContext(ctx context.Context) *BackupDatabaseInternalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the backup database internal params
func (o *BackupDatabaseInternalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the backup database internal params
func (o *BackupDatabaseInternalParams) WithHTTPClient(client *http.Client) *BackupDatabaseInternalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the backup database internal params
func (o *BackupDatabaseInternalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the backup database internal params
func (o *BackupDatabaseInternalParams) WithBody(body *model.SdxDatabaseBackupRequest) *BackupDatabaseInternalParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the backup database internal params
func (o *BackupDatabaseInternalParams) SetBody(body *model.SdxDatabaseBackupRequest) {
	o.Body = body
}

// WithName adds the name to the backup database internal params
func (o *BackupDatabaseInternalParams) WithName(name string) *BackupDatabaseInternalParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the backup database internal params
func (o *BackupDatabaseInternalParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *BackupDatabaseInternalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
