// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewBackupDatalakeStatusParams creates a new BackupDatalakeStatusParams object
// with the default values initialized.
func NewBackupDatalakeStatusParams() *BackupDatalakeStatusParams {
	var ()
	return &BackupDatalakeStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBackupDatalakeStatusParamsWithTimeout creates a new BackupDatalakeStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBackupDatalakeStatusParamsWithTimeout(timeout time.Duration) *BackupDatalakeStatusParams {
	var ()
	return &BackupDatalakeStatusParams{

		timeout: timeout,
	}
}

// NewBackupDatalakeStatusParamsWithContext creates a new BackupDatalakeStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewBackupDatalakeStatusParamsWithContext(ctx context.Context) *BackupDatalakeStatusParams {
	var ()
	return &BackupDatalakeStatusParams{

		Context: ctx,
	}
}

// NewBackupDatalakeStatusParamsWithHTTPClient creates a new BackupDatalakeStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBackupDatalakeStatusParamsWithHTTPClient(client *http.Client) *BackupDatalakeStatusParams {
	var ()
	return &BackupDatalakeStatusParams{
		HTTPClient: client,
	}
}

/*BackupDatalakeStatusParams contains all the parameters to send to the API endpoint
for the backup datalake status operation typically these are written to a http.Request
*/
type BackupDatalakeStatusParams struct {

	/*BackupID*/
	BackupID *string
	/*BackupName*/
	BackupName *string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the backup datalake status params
func (o *BackupDatalakeStatusParams) WithTimeout(timeout time.Duration) *BackupDatalakeStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the backup datalake status params
func (o *BackupDatalakeStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the backup datalake status params
func (o *BackupDatalakeStatusParams) WithContext(ctx context.Context) *BackupDatalakeStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the backup datalake status params
func (o *BackupDatalakeStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the backup datalake status params
func (o *BackupDatalakeStatusParams) WithHTTPClient(client *http.Client) *BackupDatalakeStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the backup datalake status params
func (o *BackupDatalakeStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackupID adds the backupID to the backup datalake status params
func (o *BackupDatalakeStatusParams) WithBackupID(backupID *string) *BackupDatalakeStatusParams {
	o.SetBackupID(backupID)
	return o
}

// SetBackupID adds the backupId to the backup datalake status params
func (o *BackupDatalakeStatusParams) SetBackupID(backupID *string) {
	o.BackupID = backupID
}

// WithBackupName adds the backupName to the backup datalake status params
func (o *BackupDatalakeStatusParams) WithBackupName(backupName *string) *BackupDatalakeStatusParams {
	o.SetBackupName(backupName)
	return o
}

// SetBackupName adds the backupName to the backup datalake status params
func (o *BackupDatalakeStatusParams) SetBackupName(backupName *string) {
	o.BackupName = backupName
}

// WithName adds the name to the backup datalake status params
func (o *BackupDatalakeStatusParams) WithName(name string) *BackupDatalakeStatusParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the backup datalake status params
func (o *BackupDatalakeStatusParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *BackupDatalakeStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BackupID != nil {

		// query param backupId
		var qrBackupID string
		if o.BackupID != nil {
			qrBackupID = *o.BackupID
		}
		qBackupID := qrBackupID
		if qBackupID != "" {
			if err := r.SetQueryParam("backupId", qBackupID); err != nil {
				return err
			}
		}

	}

	if o.BackupName != nil {

		// query param backupName
		var qrBackupName string
		if o.BackupName != nil {
			qrBackupName = *o.BackupName
		}
		qBackupName := qrBackupName
		if qBackupName != "" {
			if err := r.SetQueryParam("backupName", qBackupName); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
