// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCheckForStackUpgradeByCrnParams creates a new CheckForStackUpgradeByCrnParams object
// with the default values initialized.
func NewCheckForStackUpgradeByCrnParams() *CheckForStackUpgradeByCrnParams {
	var ()
	return &CheckForStackUpgradeByCrnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCheckForStackUpgradeByCrnParamsWithTimeout creates a new CheckForStackUpgradeByCrnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCheckForStackUpgradeByCrnParamsWithTimeout(timeout time.Duration) *CheckForStackUpgradeByCrnParams {
	var ()
	return &CheckForStackUpgradeByCrnParams{

		timeout: timeout,
	}
}

// NewCheckForStackUpgradeByCrnParamsWithContext creates a new CheckForStackUpgradeByCrnParams object
// with the default values initialized, and the ability to set a context for a request
func NewCheckForStackUpgradeByCrnParamsWithContext(ctx context.Context) *CheckForStackUpgradeByCrnParams {
	var ()
	return &CheckForStackUpgradeByCrnParams{

		Context: ctx,
	}
}

// NewCheckForStackUpgradeByCrnParamsWithHTTPClient creates a new CheckForStackUpgradeByCrnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCheckForStackUpgradeByCrnParamsWithHTTPClient(client *http.Client) *CheckForStackUpgradeByCrnParams {
	var ()
	return &CheckForStackUpgradeByCrnParams{
		HTTPClient: client,
	}
}

/*CheckForStackUpgradeByCrnParams contains all the parameters to send to the API endpoint
for the check for stack upgrade by crn operation typically these are written to a http.Request
*/
type CheckForStackUpgradeByCrnParams struct {

	/*Crn*/
	Crn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the check for stack upgrade by crn params
func (o *CheckForStackUpgradeByCrnParams) WithTimeout(timeout time.Duration) *CheckForStackUpgradeByCrnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check for stack upgrade by crn params
func (o *CheckForStackUpgradeByCrnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check for stack upgrade by crn params
func (o *CheckForStackUpgradeByCrnParams) WithContext(ctx context.Context) *CheckForStackUpgradeByCrnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check for stack upgrade by crn params
func (o *CheckForStackUpgradeByCrnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check for stack upgrade by crn params
func (o *CheckForStackUpgradeByCrnParams) WithHTTPClient(client *http.Client) *CheckForStackUpgradeByCrnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check for stack upgrade by crn params
func (o *CheckForStackUpgradeByCrnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCrn adds the crn to the check for stack upgrade by crn params
func (o *CheckForStackUpgradeByCrnParams) WithCrn(crn string) *CheckForStackUpgradeByCrnParams {
	o.SetCrn(crn)
	return o
}

// SetCrn adds the crn to the check for stack upgrade by crn params
func (o *CheckForStackUpgradeByCrnParams) SetCrn(crn string) {
	o.Crn = crn
}

// WriteToRequest writes these params to a swagger request
func (o *CheckForStackUpgradeByCrnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param crn
	if err := r.SetPathParam("crn", o.Crn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
