// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-sdx/model"
)

// NewDetachRecipesByNameParams creates a new DetachRecipesByNameParams object
// with the default values initialized.
func NewDetachRecipesByNameParams() *DetachRecipesByNameParams {
	var ()
	return &DetachRecipesByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDetachRecipesByNameParamsWithTimeout creates a new DetachRecipesByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDetachRecipesByNameParamsWithTimeout(timeout time.Duration) *DetachRecipesByNameParams {
	var ()
	return &DetachRecipesByNameParams{

		timeout: timeout,
	}
}

// NewDetachRecipesByNameParamsWithContext creates a new DetachRecipesByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDetachRecipesByNameParamsWithContext(ctx context.Context) *DetachRecipesByNameParams {
	var ()
	return &DetachRecipesByNameParams{

		Context: ctx,
	}
}

// NewDetachRecipesByNameParamsWithHTTPClient creates a new DetachRecipesByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDetachRecipesByNameParamsWithHTTPClient(client *http.Client) *DetachRecipesByNameParams {
	var ()
	return &DetachRecipesByNameParams{
		HTTPClient: client,
	}
}

/*DetachRecipesByNameParams contains all the parameters to send to the API endpoint
for the detach recipes by name operation typically these are written to a http.Request
*/
type DetachRecipesByNameParams struct {

	/*Body*/
	Body *model.DetachRecipeV4Request
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the detach recipes by name params
func (o *DetachRecipesByNameParams) WithTimeout(timeout time.Duration) *DetachRecipesByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the detach recipes by name params
func (o *DetachRecipesByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the detach recipes by name params
func (o *DetachRecipesByNameParams) WithContext(ctx context.Context) *DetachRecipesByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the detach recipes by name params
func (o *DetachRecipesByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the detach recipes by name params
func (o *DetachRecipesByNameParams) WithHTTPClient(client *http.Client) *DetachRecipesByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the detach recipes by name params
func (o *DetachRecipesByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the detach recipes by name params
func (o *DetachRecipesByNameParams) WithBody(body *model.DetachRecipeV4Request) *DetachRecipesByNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the detach recipes by name params
func (o *DetachRecipesByNameParams) SetBody(body *model.DetachRecipeV4Request) {
	o.Body = body
}

// WithName adds the name to the detach recipes by name params
func (o *DetachRecipesByNameParams) WithName(name string) *DetachRecipesByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the detach recipes by name params
func (o *DetachRecipesByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DetachRecipesByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
