// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetInstanceGroupNamesBySdxDetailsReader is a Reader for the GetInstanceGroupNamesBySdxDetails structure.
type GetInstanceGroupNamesBySdxDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstanceGroupNamesBySdxDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInstanceGroupNamesBySdxDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInstanceGroupNamesBySdxDetailsOK creates a GetInstanceGroupNamesBySdxDetailsOK with default headers values
func NewGetInstanceGroupNamesBySdxDetailsOK() *GetInstanceGroupNamesBySdxDetailsOK {
	return &GetInstanceGroupNamesBySdxDetailsOK{}
}

/*GetInstanceGroupNamesBySdxDetailsOK handles this case with default header values.

successful operation
*/
type GetInstanceGroupNamesBySdxDetailsOK struct {
	Payload []string
}

func (o *GetInstanceGroupNamesBySdxDetailsOK) Error() string {
	return fmt.Sprintf("[GET /sdx/instance_group_names][%d] getInstanceGroupNamesBySdxDetailsOK  %+v", 200, o.Payload)
}

func (o *GetInstanceGroupNamesBySdxDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
