// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-sdx/model"
)

// GetBackupDatalakeStatusReader is a Reader for the GetBackupDatalakeStatus structure.
type GetBackupDatalakeStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBackupDatalakeStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBackupDatalakeStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBackupDatalakeStatusOK creates a GetBackupDatalakeStatusOK with default headers values
func NewGetBackupDatalakeStatusOK() *GetBackupDatalakeStatusOK {
	return &GetBackupDatalakeStatusOK{}
}

/*
GetBackupDatalakeStatusOK handles this case with default header values.

successful operation
*/
type GetBackupDatalakeStatusOK struct {
	Payload *model.SdxBackupStatusResponse
}

func (o *GetBackupDatalakeStatusOK) Error() string {
	return fmt.Sprintf("[GET /sdx/{name}/getBackupDatalakeStatus][%d] getBackupDatalakeStatusOK  %+v", 200, o.Payload)
}

func (o *GetBackupDatalakeStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.SdxBackupStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
