// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-sdx/model"
)

// SyncCmOnDatalakeClusterReader is a Reader for the SyncCmOnDatalakeCluster structure.
type SyncCmOnDatalakeClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SyncCmOnDatalakeClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSyncCmOnDatalakeClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSyncCmOnDatalakeClusterOK creates a SyncCmOnDatalakeClusterOK with default headers values
func NewSyncCmOnDatalakeClusterOK() *SyncCmOnDatalakeClusterOK {
	return &SyncCmOnDatalakeClusterOK{}
}

/*
SyncCmOnDatalakeClusterOK handles this case with default header values.

successful operation
*/
type SyncCmOnDatalakeClusterOK struct {
	Payload *model.SdxSyncComponentVersionsFromCmResponse
}

func (o *SyncCmOnDatalakeClusterOK) Error() string {
	return fmt.Sprintf("[POST /sdx/{name}/sync_component_versions_from_cm][%d] syncCmOnDatalakeClusterOK  %+v", 200, o.Payload)
}

func (o *SyncCmOnDatalakeClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.SdxSyncComponentVersionsFromCmResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
