// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpgradeClusterByCrnParams creates a new UpgradeClusterByCrnParams object
// with the default values initialized.
func NewUpgradeClusterByCrnParams() *UpgradeClusterByCrnParams {
	var ()
	return &UpgradeClusterByCrnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpgradeClusterByCrnParamsWithTimeout creates a new UpgradeClusterByCrnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpgradeClusterByCrnParamsWithTimeout(timeout time.Duration) *UpgradeClusterByCrnParams {
	var ()
	return &UpgradeClusterByCrnParams{

		timeout: timeout,
	}
}

// NewUpgradeClusterByCrnParamsWithContext creates a new UpgradeClusterByCrnParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpgradeClusterByCrnParamsWithContext(ctx context.Context) *UpgradeClusterByCrnParams {
	var ()
	return &UpgradeClusterByCrnParams{

		Context: ctx,
	}
}

// NewUpgradeClusterByCrnParamsWithHTTPClient creates a new UpgradeClusterByCrnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpgradeClusterByCrnParamsWithHTTPClient(client *http.Client) *UpgradeClusterByCrnParams {
	var ()
	return &UpgradeClusterByCrnParams{
		HTTPClient: client,
	}
}

/*UpgradeClusterByCrnParams contains all the parameters to send to the API endpoint
for the upgrade cluster by crn operation typically these are written to a http.Request
*/
type UpgradeClusterByCrnParams struct {

	/*Crn*/
	Crn string
	/*Image*/
	Image string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) WithTimeout(timeout time.Duration) *UpgradeClusterByCrnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) WithContext(ctx context.Context) *UpgradeClusterByCrnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) WithHTTPClient(client *http.Client) *UpgradeClusterByCrnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCrn adds the crn to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) WithCrn(crn string) *UpgradeClusterByCrnParams {
	o.SetCrn(crn)
	return o
}

// SetCrn adds the crn to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) SetCrn(crn string) {
	o.Crn = crn
}

// WithImage adds the image to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) WithImage(image string) *UpgradeClusterByCrnParams {
	o.SetImage(image)
	return o
}

// SetImage adds the image to the upgrade cluster by crn params
func (o *UpgradeClusterByCrnParams) SetImage(image string) {
	o.Image = image
}

// WriteToRequest writes these params to a swagger request
func (o *UpgradeClusterByCrnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param crn
	if err := r.SetPathParam("crn", o.Crn); err != nil {
		return err
	}

	// path param image
	if err := r.SetPathParam("image", o.Image); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
