// Code generated by go-swagger; DO NOT EDIT.

package sdx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/dataplane/api-sdx/model"
)

// UpgradeDatalakeClusterByCrnReader is a Reader for the UpgradeDatalakeClusterByCrn structure.
type UpgradeDatalakeClusterByCrnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpgradeDatalakeClusterByCrnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpgradeDatalakeClusterByCrnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpgradeDatalakeClusterByCrnOK creates a UpgradeDatalakeClusterByCrnOK with default headers values
func NewUpgradeDatalakeClusterByCrnOK() *UpgradeDatalakeClusterByCrnOK {
	return &UpgradeDatalakeClusterByCrnOK{}
}

/*
UpgradeDatalakeClusterByCrnOK handles this case with default header values.

successful operation
*/
type UpgradeDatalakeClusterByCrnOK struct {
	Payload *model.SdxUpgradeResponse
}

func (o *UpgradeDatalakeClusterByCrnOK) Error() string {
	return fmt.Sprintf("[POST /sdx/crn/{crn}/upgrade][%d] upgradeDatalakeClusterByCrnOK  %+v", 200, o.Payload)
}

func (o *UpgradeDatalakeClusterByCrnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.SdxUpgradeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
