// Code generated by go-swagger; DO NOT EDIT.

package v1distroxcost

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListDistroXCostV1Params creates a new ListDistroXCostV1Params object
// with the default values initialized.
func NewListDistroXCostV1Params() *ListDistroXCostV1Params {
	var ()
	return &ListDistroXCostV1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewListDistroXCostV1ParamsWithTimeout creates a new ListDistroXCostV1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDistroXCostV1ParamsWithTimeout(timeout time.Duration) *ListDistroXCostV1Params {
	var ()
	return &ListDistroXCostV1Params{

		timeout: timeout,
	}
}

// NewListDistroXCostV1ParamsWithContext creates a new ListDistroXCostV1Params object
// with the default values initialized, and the ability to set a context for a request
func NewListDistroXCostV1ParamsWithContext(ctx context.Context) *ListDistroXCostV1Params {
	var ()
	return &ListDistroXCostV1Params{

		Context: ctx,
	}
}

// NewListDistroXCostV1ParamsWithHTTPClient creates a new ListDistroXCostV1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDistroXCostV1ParamsWithHTTPClient(client *http.Client) *ListDistroXCostV1Params {
	var ()
	return &ListDistroXCostV1Params{
		HTTPClient: client,
	}
}

/*
ListDistroXCostV1Params contains all the parameters to send to the API endpoint
for the list distro x cost v1 operation typically these are written to a http.Request
*/
type ListDistroXCostV1Params struct {

	/*Body*/
	Body []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list distro x cost v1 params
func (o *ListDistroXCostV1Params) WithTimeout(timeout time.Duration) *ListDistroXCostV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list distro x cost v1 params
func (o *ListDistroXCostV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list distro x cost v1 params
func (o *ListDistroXCostV1Params) WithContext(ctx context.Context) *ListDistroXCostV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list distro x cost v1 params
func (o *ListDistroXCostV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list distro x cost v1 params
func (o *ListDistroXCostV1Params) WithHTTPClient(client *http.Client) *ListDistroXCostV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list distro x cost v1 params
func (o *ListDistroXCostV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the list distro x cost v1 params
func (o *ListDistroXCostV1Params) WithBody(body []string) *ListDistroXCostV1Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the list distro x cost v1 params
func (o *ListDistroXCostV1Params) SetBody(body []string) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ListDistroXCostV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
