// Code generated by go-swagger; DO NOT EDIT.

package v2clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDisableAutoscaleStateByCloudbreakClusterParams creates a new DisableAutoscaleStateByCloudbreakClusterParams object
// with the default values initialized.
func NewDisableAutoscaleStateByCloudbreakClusterParams() *DisableAutoscaleStateByCloudbreakClusterParams {
	var ()
	return &DisableAutoscaleStateByCloudbreakClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDisableAutoscaleStateByCloudbreakClusterParamsWithTimeout creates a new DisableAutoscaleStateByCloudbreakClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDisableAutoscaleStateByCloudbreakClusterParamsWithTimeout(timeout time.Duration) *DisableAutoscaleStateByCloudbreakClusterParams {
	var ()
	return &DisableAutoscaleStateByCloudbreakClusterParams{

		timeout: timeout,
	}
}

// NewDisableAutoscaleStateByCloudbreakClusterParamsWithContext creates a new DisableAutoscaleStateByCloudbreakClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewDisableAutoscaleStateByCloudbreakClusterParamsWithContext(ctx context.Context) *DisableAutoscaleStateByCloudbreakClusterParams {
	var ()
	return &DisableAutoscaleStateByCloudbreakClusterParams{

		Context: ctx,
	}
}

// NewDisableAutoscaleStateByCloudbreakClusterParamsWithHTTPClient creates a new DisableAutoscaleStateByCloudbreakClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDisableAutoscaleStateByCloudbreakClusterParamsWithHTTPClient(client *http.Client) *DisableAutoscaleStateByCloudbreakClusterParams {
	var ()
	return &DisableAutoscaleStateByCloudbreakClusterParams{
		HTTPClient: client,
	}
}

/*DisableAutoscaleStateByCloudbreakClusterParams contains all the parameters to send to the API endpoint
for the disable autoscale state by cloudbreak cluster operation typically these are written to a http.Request
*/
type DisableAutoscaleStateByCloudbreakClusterParams struct {

	/*CbClusterID*/
	CbClusterID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the disable autoscale state by cloudbreak cluster params
func (o *DisableAutoscaleStateByCloudbreakClusterParams) WithTimeout(timeout time.Duration) *DisableAutoscaleStateByCloudbreakClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disable autoscale state by cloudbreak cluster params
func (o *DisableAutoscaleStateByCloudbreakClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disable autoscale state by cloudbreak cluster params
func (o *DisableAutoscaleStateByCloudbreakClusterParams) WithContext(ctx context.Context) *DisableAutoscaleStateByCloudbreakClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disable autoscale state by cloudbreak cluster params
func (o *DisableAutoscaleStateByCloudbreakClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the disable autoscale state by cloudbreak cluster params
func (o *DisableAutoscaleStateByCloudbreakClusterParams) WithHTTPClient(client *http.Client) *DisableAutoscaleStateByCloudbreakClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the disable autoscale state by cloudbreak cluster params
func (o *DisableAutoscaleStateByCloudbreakClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCbClusterID adds the cbClusterID to the disable autoscale state by cloudbreak cluster params
func (o *DisableAutoscaleStateByCloudbreakClusterParams) WithCbClusterID(cbClusterID int64) *DisableAutoscaleStateByCloudbreakClusterParams {
	o.SetCbClusterID(cbClusterID)
	return o
}

// SetCbClusterID adds the cbClusterId to the disable autoscale state by cloudbreak cluster params
func (o *DisableAutoscaleStateByCloudbreakClusterParams) SetCbClusterID(cbClusterID int64) {
	o.CbClusterID = cbClusterID
}

// WriteToRequest writes these params to a swagger request
func (o *DisableAutoscaleStateByCloudbreakClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cbClusterId
	if err := r.SetPathParam("cbClusterId", swag.FormatInt64(o.CbClusterID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
