// Code generated by go-swagger; DO NOT EDIT.

package v2clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/cloudbreak/api-as/model"
)

// DisableAutoscaleStateByCloudbreakClusterReader is a Reader for the DisableAutoscaleStateByCloudbreakCluster structure.
type DisableAutoscaleStateByCloudbreakClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisableAutoscaleStateByCloudbreakClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDisableAutoscaleStateByCloudbreakClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDisableAutoscaleStateByCloudbreakClusterOK creates a DisableAutoscaleStateByCloudbreakClusterOK with default headers values
func NewDisableAutoscaleStateByCloudbreakClusterOK() *DisableAutoscaleStateByCloudbreakClusterOK {
	return &DisableAutoscaleStateByCloudbreakClusterOK{}
}

/*DisableAutoscaleStateByCloudbreakClusterOK handles this case with default header values.

successful operation
*/
type DisableAutoscaleStateByCloudbreakClusterOK struct {
	Payload *model.AutoscaleClusterResponse
}

func (o *DisableAutoscaleStateByCloudbreakClusterOK) Error() string {
	return fmt.Sprintf("[POST /v2/clusters/{cbClusterId}/disable][%d] disableAutoscaleStateByCloudbreakClusterOK  %+v", 200, o.Payload)
}

func (o *DisableAutoscaleStateByCloudbreakClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.AutoscaleClusterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
