// Code generated by go-swagger; DO NOT EDIT.

package v2clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	model "github.com/hortonworks/cb-cli/cloudbreak/api-as/model"
)

// ModifyByCloudbreakClusterReader is a Reader for the ModifyByCloudbreakCluster structure.
type ModifyByCloudbreakClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyByCloudbreakClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyByCloudbreakClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyByCloudbreakClusterOK creates a ModifyByCloudbreakClusterOK with default headers values
func NewModifyByCloudbreakClusterOK() *ModifyByCloudbreakClusterOK {
	return &ModifyByCloudbreakClusterOK{}
}

/*ModifyByCloudbreakClusterOK handles this case with default header values.

successful operation
*/
type ModifyByCloudbreakClusterOK struct {
	Payload *model.AutoscaleClusterResponse
}

func (o *ModifyByCloudbreakClusterOK) Error() string {
	return fmt.Sprintf("[PUT /v2/clusters/{cbClusterId}][%d] modifyByCloudbreakClusterOK  %+v", 200, o.Payload)
}

func (o *ModifyByCloudbreakClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.AutoscaleClusterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
