// Code generated by go-swagger; DO NOT EDIT.

package v2clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSuspendByCloudbreakClusterParams creates a new SuspendByCloudbreakClusterParams object
// with the default values initialized.
func NewSuspendByCloudbreakClusterParams() *SuspendByCloudbreakClusterParams {
	var ()
	return &SuspendByCloudbreakClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSuspendByCloudbreakClusterParamsWithTimeout creates a new SuspendByCloudbreakClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSuspendByCloudbreakClusterParamsWithTimeout(timeout time.Duration) *SuspendByCloudbreakClusterParams {
	var ()
	return &SuspendByCloudbreakClusterParams{

		timeout: timeout,
	}
}

// NewSuspendByCloudbreakClusterParamsWithContext creates a new SuspendByCloudbreakClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewSuspendByCloudbreakClusterParamsWithContext(ctx context.Context) *SuspendByCloudbreakClusterParams {
	var ()
	return &SuspendByCloudbreakClusterParams{

		Context: ctx,
	}
}

// NewSuspendByCloudbreakClusterParamsWithHTTPClient creates a new SuspendByCloudbreakClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSuspendByCloudbreakClusterParamsWithHTTPClient(client *http.Client) *SuspendByCloudbreakClusterParams {
	var ()
	return &SuspendByCloudbreakClusterParams{
		HTTPClient: client,
	}
}

/*SuspendByCloudbreakClusterParams contains all the parameters to send to the API endpoint
for the suspend by cloudbreak cluster operation typically these are written to a http.Request
*/
type SuspendByCloudbreakClusterParams struct {

	/*CbClusterID*/
	CbClusterID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the suspend by cloudbreak cluster params
func (o *SuspendByCloudbreakClusterParams) WithTimeout(timeout time.Duration) *SuspendByCloudbreakClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the suspend by cloudbreak cluster params
func (o *SuspendByCloudbreakClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the suspend by cloudbreak cluster params
func (o *SuspendByCloudbreakClusterParams) WithContext(ctx context.Context) *SuspendByCloudbreakClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the suspend by cloudbreak cluster params
func (o *SuspendByCloudbreakClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the suspend by cloudbreak cluster params
func (o *SuspendByCloudbreakClusterParams) WithHTTPClient(client *http.Client) *SuspendByCloudbreakClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the suspend by cloudbreak cluster params
func (o *SuspendByCloudbreakClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCbClusterID adds the cbClusterID to the suspend by cloudbreak cluster params
func (o *SuspendByCloudbreakClusterParams) WithCbClusterID(cbClusterID int64) *SuspendByCloudbreakClusterParams {
	o.SetCbClusterID(cbClusterID)
	return o
}

// SetCbClusterID adds the cbClusterId to the suspend by cloudbreak cluster params
func (o *SuspendByCloudbreakClusterParams) SetCbClusterID(cbClusterID int64) {
	o.CbClusterID = cbClusterID
}

// WriteToRequest writes these params to a swagger request
func (o *SuspendByCloudbreakClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cbClusterId
	if err := r.SetPathParam("cbClusterId", swag.FormatInt64(o.CbClusterID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
