// Code generated by go-swagger; DO NOT EDIT.

package v1alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteMetricAlarmReader is a Reader for the DeleteMetricAlarm structure.
type DeleteMetricAlarmReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMetricAlarmReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewDeleteMetricAlarmDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewDeleteMetricAlarmDefault creates a DeleteMetricAlarmDefault with default headers values
func NewDeleteMetricAlarmDefault(code int) *DeleteMetricAlarmDefault {
	return &DeleteMetricAlarmDefault{
		_statusCode: code,
	}
}

/*DeleteMetricAlarmDefault handles this case with default header values.

successful operation
*/
type DeleteMetricAlarmDefault struct {
	_statusCode int
}

// Code gets the status code for the delete metric alarm default response
func (o *DeleteMetricAlarmDefault) Code() int {
	return o._statusCode
}

func (o *DeleteMetricAlarmDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/clusters/{clusterId}/alerts/metric/{alertId}][%d] deleteMetricAlarm default ", o._statusCode)
}

func (o *DeleteMetricAlarmDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
