// Code generated by go-swagger; DO NOT EDIT.

package flow_logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewHasFlowRunningByFlowIDParams creates a new HasFlowRunningByFlowIDParams object
// with the default values initialized.
func NewHasFlowRunningByFlowIDParams() *HasFlowRunningByFlowIDParams {
	var ()
	return &HasFlowRunningByFlowIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHasFlowRunningByFlowIDParamsWithTimeout creates a new HasFlowRunningByFlowIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHasFlowRunningByFlowIDParamsWithTimeout(timeout time.Duration) *HasFlowRunningByFlowIDParams {
	var ()
	return &HasFlowRunningByFlowIDParams{

		timeout: timeout,
	}
}

// NewHasFlowRunningByFlowIDParamsWithContext creates a new HasFlowRunningByFlowIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewHasFlowRunningByFlowIDParamsWithContext(ctx context.Context) *HasFlowRunningByFlowIDParams {
	var ()
	return &HasFlowRunningByFlowIDParams{

		Context: ctx,
	}
}

// NewHasFlowRunningByFlowIDParamsWithHTTPClient creates a new HasFlowRunningByFlowIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHasFlowRunningByFlowIDParamsWithHTTPClient(client *http.Client) *HasFlowRunningByFlowIDParams {
	var ()
	return &HasFlowRunningByFlowIDParams{
		HTTPClient: client,
	}
}

/*HasFlowRunningByFlowIDParams contains all the parameters to send to the API endpoint
for the has flow running by flow Id operation typically these are written to a http.Request
*/
type HasFlowRunningByFlowIDParams struct {

	/*FlowID*/
	FlowID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the has flow running by flow Id params
func (o *HasFlowRunningByFlowIDParams) WithTimeout(timeout time.Duration) *HasFlowRunningByFlowIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the has flow running by flow Id params
func (o *HasFlowRunningByFlowIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the has flow running by flow Id params
func (o *HasFlowRunningByFlowIDParams) WithContext(ctx context.Context) *HasFlowRunningByFlowIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the has flow running by flow Id params
func (o *HasFlowRunningByFlowIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the has flow running by flow Id params
func (o *HasFlowRunningByFlowIDParams) WithHTTPClient(client *http.Client) *HasFlowRunningByFlowIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the has flow running by flow Id params
func (o *HasFlowRunningByFlowIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFlowID adds the flowID to the has flow running by flow Id params
func (o *HasFlowRunningByFlowIDParams) WithFlowID(flowID string) *HasFlowRunningByFlowIDParams {
	o.SetFlowID(flowID)
	return o
}

// SetFlowID adds the flowId to the has flow running by flow Id params
func (o *HasFlowRunningByFlowIDParams) SetFlowID(flowID string) {
	o.FlowID = flowID
}

// WriteToRequest writes these params to a swagger request
func (o *HasFlowRunningByFlowIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param flowId
	if err := r.SetPathParam("flowId", o.FlowID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
