// Code generated by go-swagger; DO NOT EDIT.

package v4customimagecatalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCustomImageCatalogByNameParams creates a new DeleteCustomImageCatalogByNameParams object
// with the default values initialized.
func NewDeleteCustomImageCatalogByNameParams() *DeleteCustomImageCatalogByNameParams {
	var ()
	return &DeleteCustomImageCatalogByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCustomImageCatalogByNameParamsWithTimeout creates a new DeleteCustomImageCatalogByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCustomImageCatalogByNameParamsWithTimeout(timeout time.Duration) *DeleteCustomImageCatalogByNameParams {
	var ()
	return &DeleteCustomImageCatalogByNameParams{

		timeout: timeout,
	}
}

// NewDeleteCustomImageCatalogByNameParamsWithContext creates a new DeleteCustomImageCatalogByNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCustomImageCatalogByNameParamsWithContext(ctx context.Context) *DeleteCustomImageCatalogByNameParams {
	var ()
	return &DeleteCustomImageCatalogByNameParams{

		Context: ctx,
	}
}

// NewDeleteCustomImageCatalogByNameParamsWithHTTPClient creates a new DeleteCustomImageCatalogByNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCustomImageCatalogByNameParamsWithHTTPClient(client *http.Client) *DeleteCustomImageCatalogByNameParams {
	var ()
	return &DeleteCustomImageCatalogByNameParams{
		HTTPClient: client,
	}
}

/*DeleteCustomImageCatalogByNameParams contains all the parameters to send to the API endpoint
for the delete custom image catalog by name operation typically these are written to a http.Request
*/
type DeleteCustomImageCatalogByNameParams struct {

	/*AccountID*/
	AccountID *string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) WithTimeout(timeout time.Duration) *DeleteCustomImageCatalogByNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) WithContext(ctx context.Context) *DeleteCustomImageCatalogByNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) WithHTTPClient(client *http.Client) *DeleteCustomImageCatalogByNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) WithAccountID(accountID *string) *DeleteCustomImageCatalogByNameParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) SetAccountID(accountID *string) {
	o.AccountID = accountID
}

// WithName adds the name to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) WithName(name string) *DeleteCustomImageCatalogByNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete custom image catalog by name params
func (o *DeleteCustomImageCatalogByNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCustomImageCatalogByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccountID != nil {

		// query param accountId
		var qrAccountID string
		if o.AccountID != nil {
			qrAccountID = *o.AccountID
		}
		qAccountID := qrAccountID
		if qAccountID != "" {
			if err := r.SetQueryParam("accountId", qAccountID); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
