// Code generated by go-swagger; DO NOT EDIT.

package v1freeipa

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RotateSaltPasswordV1Reader is a Reader for the RotateSaltPasswordV1 structure.
type RotateSaltPasswordV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RotateSaltPasswordV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewRotateSaltPasswordV1Default(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewRotateSaltPasswordV1Default creates a RotateSaltPasswordV1Default with default headers values
func NewRotateSaltPasswordV1Default(code int) *RotateSaltPasswordV1Default {
	return &RotateSaltPasswordV1Default{
		_statusCode: code,
	}
}

/*RotateSaltPasswordV1Default handles this case with default header values.

successful operation
*/
type RotateSaltPasswordV1Default struct {
	_statusCode int
}

// Code gets the status code for the rotate salt password v1 default response
func (o *RotateSaltPasswordV1Default) Code() int {
	return o._statusCode
}

func (o *RotateSaltPasswordV1Default) Error() string {
	return fmt.Sprintf("[POST /v1/freeipa/rotate_salt_password][%d] rotateSaltPasswordV1 default ", o._statusCode)
}

func (o *RotateSaltPasswordV1Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
