// Code generated by go-swagger; DO NOT EDIT.

package v1progress

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFreeIpaLastFlowLogProgressByEnvironmentCrnParams creates a new GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams object
// with the default values initialized.
func NewGetFreeIpaLastFlowLogProgressByEnvironmentCrnParams() *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams {
	var ()
	return &GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFreeIpaLastFlowLogProgressByEnvironmentCrnParamsWithTimeout creates a new GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFreeIpaLastFlowLogProgressByEnvironmentCrnParamsWithTimeout(timeout time.Duration) *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams {
	var ()
	return &GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams{

		timeout: timeout,
	}
}

// NewGetFreeIpaLastFlowLogProgressByEnvironmentCrnParamsWithContext creates a new GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFreeIpaLastFlowLogProgressByEnvironmentCrnParamsWithContext(ctx context.Context) *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams {
	var ()
	return &GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams{

		Context: ctx,
	}
}

// NewGetFreeIpaLastFlowLogProgressByEnvironmentCrnParamsWithHTTPClient creates a new GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFreeIpaLastFlowLogProgressByEnvironmentCrnParamsWithHTTPClient(client *http.Client) *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams {
	var ()
	return &GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams{
		HTTPClient: client,
	}
}

/*
GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams contains all the parameters to send to the API endpoint
for the get free ipa last flow log progress by environment crn operation typically these are written to a http.Request
*/
type GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams struct {

	/*EnvironmentCrn*/
	EnvironmentCrn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get free ipa last flow log progress by environment crn params
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) WithTimeout(timeout time.Duration) *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get free ipa last flow log progress by environment crn params
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get free ipa last flow log progress by environment crn params
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) WithContext(ctx context.Context) *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get free ipa last flow log progress by environment crn params
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get free ipa last flow log progress by environment crn params
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) WithHTTPClient(client *http.Client) *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get free ipa last flow log progress by environment crn params
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnvironmentCrn adds the environmentCrn to the get free ipa last flow log progress by environment crn params
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) WithEnvironmentCrn(environmentCrn string) *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams {
	o.SetEnvironmentCrn(environmentCrn)
	return o
}

// SetEnvironmentCrn adds the environmentCrn to the get free ipa last flow log progress by environment crn params
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) SetEnvironmentCrn(environmentCrn string) {
	o.EnvironmentCrn = environmentCrn
}

// WriteToRequest writes these params to a swagger request
func (o *GetFreeIpaLastFlowLogProgressByEnvironmentCrnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param environmentCrn
	if err := r.SetPathParam("environmentCrn", o.EnvironmentCrn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
