// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AttachChildEnvironmentV1Request attach child environment v1 request
// swagger:model AttachChildEnvironmentV1Request
type AttachChildEnvironmentV1Request struct {

	// CRN of the child environment
	// Required: true
	ChildEnvironmentCrn *string `json:"childEnvironmentCrn"`

	// CRN of the parent environment
	// Required: true
	ParentEnvironmentCrn *string `json:"parentEnvironmentCrn"`
}

// Validate validates this attach child environment v1 request
func (m *AttachChildEnvironmentV1Request) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChildEnvironmentCrn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParentEnvironmentCrn(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AttachChildEnvironmentV1Request) validateChildEnvironmentCrn(formats strfmt.Registry) error {

	if err := validate.Required("childEnvironmentCrn", "body", m.ChildEnvironmentCrn); err != nil {
		return err
	}

	return nil
}

func (m *AttachChildEnvironmentV1Request) validateParentEnvironmentCrn(formats strfmt.Registry) error {

	if err := validate.Required("parentEnvironmentCrn", "body", m.ParentEnvironmentCrn); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AttachChildEnvironmentV1Request) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AttachChildEnvironmentV1Request) UnmarshalBinary(b []byte) error {
	var res AttachChildEnvironmentV1Request
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
