// Code generated by go-swagger; DO NOT EDIT.

package v4progress

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRedbeamsFlowLogsProgressByResourceCrnParams creates a new GetRedbeamsFlowLogsProgressByResourceCrnParams object
// with the default values initialized.
func NewGetRedbeamsFlowLogsProgressByResourceCrnParams() *GetRedbeamsFlowLogsProgressByResourceCrnParams {
	var ()
	return &GetRedbeamsFlowLogsProgressByResourceCrnParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRedbeamsFlowLogsProgressByResourceCrnParamsWithTimeout creates a new GetRedbeamsFlowLogsProgressByResourceCrnParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRedbeamsFlowLogsProgressByResourceCrnParamsWithTimeout(timeout time.Duration) *GetRedbeamsFlowLogsProgressByResourceCrnParams {
	var ()
	return &GetRedbeamsFlowLogsProgressByResourceCrnParams{

		timeout: timeout,
	}
}

// NewGetRedbeamsFlowLogsProgressByResourceCrnParamsWithContext creates a new GetRedbeamsFlowLogsProgressByResourceCrnParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRedbeamsFlowLogsProgressByResourceCrnParamsWithContext(ctx context.Context) *GetRedbeamsFlowLogsProgressByResourceCrnParams {
	var ()
	return &GetRedbeamsFlowLogsProgressByResourceCrnParams{

		Context: ctx,
	}
}

// NewGetRedbeamsFlowLogsProgressByResourceCrnParamsWithHTTPClient creates a new GetRedbeamsFlowLogsProgressByResourceCrnParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRedbeamsFlowLogsProgressByResourceCrnParamsWithHTTPClient(client *http.Client) *GetRedbeamsFlowLogsProgressByResourceCrnParams {
	var ()
	return &GetRedbeamsFlowLogsProgressByResourceCrnParams{
		HTTPClient: client,
	}
}

/*
GetRedbeamsFlowLogsProgressByResourceCrnParams contains all the parameters to send to the API endpoint
for the get redbeams flow logs progress by resource crn operation typically these are written to a http.Request
*/
type GetRedbeamsFlowLogsProgressByResourceCrnParams struct {

	/*ResourceCrn*/
	ResourceCrn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get redbeams flow logs progress by resource crn params
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) WithTimeout(timeout time.Duration) *GetRedbeamsFlowLogsProgressByResourceCrnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get redbeams flow logs progress by resource crn params
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get redbeams flow logs progress by resource crn params
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) WithContext(ctx context.Context) *GetRedbeamsFlowLogsProgressByResourceCrnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get redbeams flow logs progress by resource crn params
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get redbeams flow logs progress by resource crn params
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) WithHTTPClient(client *http.Client) *GetRedbeamsFlowLogsProgressByResourceCrnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get redbeams flow logs progress by resource crn params
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceCrn adds the resourceCrn to the get redbeams flow logs progress by resource crn params
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) WithResourceCrn(resourceCrn string) *GetRedbeamsFlowLogsProgressByResourceCrnParams {
	o.SetResourceCrn(resourceCrn)
	return o
}

// SetResourceCrn adds the resourceCrn to the get redbeams flow logs progress by resource crn params
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) SetResourceCrn(resourceCrn string) {
	o.ResourceCrn = resourceCrn
}

// WriteToRequest writes these params to a swagger request
func (o *GetRedbeamsFlowLogsProgressByResourceCrnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceCrn
	if err := r.SetPathParam("resourceCrn", o.ResourceCrn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
