// Code generated by go-swagger; DO NOT EDIT.

package database_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStopDatabaseServerParams creates a new StopDatabaseServerParams object
// with the default values initialized.
func NewStopDatabaseServerParams() *StopDatabaseServerParams {
	var ()
	return &StopDatabaseServerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStopDatabaseServerParamsWithTimeout creates a new StopDatabaseServerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStopDatabaseServerParamsWithTimeout(timeout time.Duration) *StopDatabaseServerParams {
	var ()
	return &StopDatabaseServerParams{

		timeout: timeout,
	}
}

// NewStopDatabaseServerParamsWithContext creates a new StopDatabaseServerParams object
// with the default values initialized, and the ability to set a context for a request
func NewStopDatabaseServerParamsWithContext(ctx context.Context) *StopDatabaseServerParams {
	var ()
	return &StopDatabaseServerParams{

		Context: ctx,
	}
}

// NewStopDatabaseServerParamsWithHTTPClient creates a new StopDatabaseServerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStopDatabaseServerParamsWithHTTPClient(client *http.Client) *StopDatabaseServerParams {
	var ()
	return &StopDatabaseServerParams{
		HTTPClient: client,
	}
}

/*StopDatabaseServerParams contains all the parameters to send to the API endpoint
for the stop database server operation typically these are written to a http.Request
*/
type StopDatabaseServerParams struct {

	/*Crn
	  CRN of the database server

	*/
	Crn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stop database server params
func (o *StopDatabaseServerParams) WithTimeout(timeout time.Duration) *StopDatabaseServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop database server params
func (o *StopDatabaseServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop database server params
func (o *StopDatabaseServerParams) WithContext(ctx context.Context) *StopDatabaseServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop database server params
func (o *StopDatabaseServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop database server params
func (o *StopDatabaseServerParams) WithHTTPClient(client *http.Client) *StopDatabaseServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop database server params
func (o *StopDatabaseServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCrn adds the crn to the stop database server params
func (o *StopDatabaseServerParams) WithCrn(crn string) *StopDatabaseServerParams {
	o.SetCrn(crn)
	return o
}

// SetCrn adds the crn to the stop database server params
func (o *StopDatabaseServerParams) SetCrn(crn string) {
	o.Crn = crn
}

// WriteToRequest writes these params to a swagger request
func (o *StopDatabaseServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param crn
	if err := r.SetPathParam("crn", o.Crn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
