// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/hortonworks/cb-cli/cloudbreak/api-as/client/v1alerts"
	"github.com/hortonworks/cb-cli/cloudbreak/api-as/client/v1clusters"
	"github.com/hortonworks/cb-cli/cloudbreak/api-as/client/v1configurations"
	"github.com/hortonworks/cb-cli/cloudbreak/api-as/client/v1history"
	"github.com/hortonworks/cb-cli/cloudbreak/api-as/client/v1policies"
	"github.com/hortonworks/cb-cli/cloudbreak/api-as/client/v2clusters"
)

// Default auto scaling HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new auto scaling HTTP client.
func NewHTTPClient(formats strfmt.Registry) *AutoScaling {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new auto scaling HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *AutoScaling {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new auto scaling client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *AutoScaling {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(AutoScaling)
	cli.Transport = transport

	cli.V1alerts = v1alerts.New(transport, formats)

	cli.V1clusters = v1clusters.New(transport, formats)

	cli.V1configurations = v1configurations.New(transport, formats)

	cli.V1history = v1history.New(transport, formats)

	cli.V1policies = v1policies.New(transport, formats)

	cli.V2clusters = v2clusters.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// AutoScaling is a client for auto scaling
type AutoScaling struct {
	V1alerts *v1alerts.Client

	V1clusters *v1clusters.Client

	V1configurations *v1configurations.Client

	V1history *v1history.Client

	V1policies *v1policies.Client

	V2clusters *v2clusters.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *AutoScaling) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.V1alerts.SetTransport(transport)

	c.V1clusters.SetTransport(transport)

	c.V1configurations.SetTransport(transport)

	c.V1history.SetTransport(transport)

	c.V1policies.SetTransport(transport)

	c.V2clusters.SetTransport(transport)

}
