// Code generated by go-swagger; DO NOT EDIT.

package v4_workspace_id_recipes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRecipeInWorkspaceInternalParams creates a new GetRecipeInWorkspaceInternalParams object
// with the default values initialized.
func NewGetRecipeInWorkspaceInternalParams() *GetRecipeInWorkspaceInternalParams {
	var ()
	return &GetRecipeInWorkspaceInternalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRecipeInWorkspaceInternalParamsWithTimeout creates a new GetRecipeInWorkspaceInternalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRecipeInWorkspaceInternalParamsWithTimeout(timeout time.Duration) *GetRecipeInWorkspaceInternalParams {
	var ()
	return &GetRecipeInWorkspaceInternalParams{

		timeout: timeout,
	}
}

// NewGetRecipeInWorkspaceInternalParamsWithContext creates a new GetRecipeInWorkspaceInternalParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRecipeInWorkspaceInternalParamsWithContext(ctx context.Context) *GetRecipeInWorkspaceInternalParams {
	var ()
	return &GetRecipeInWorkspaceInternalParams{

		Context: ctx,
	}
}

// NewGetRecipeInWorkspaceInternalParamsWithHTTPClient creates a new GetRecipeInWorkspaceInternalParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRecipeInWorkspaceInternalParamsWithHTTPClient(client *http.Client) *GetRecipeInWorkspaceInternalParams {
	var ()
	return &GetRecipeInWorkspaceInternalParams{
		HTTPClient: client,
	}
}

/*GetRecipeInWorkspaceInternalParams contains all the parameters to send to the API endpoint
for the get recipe in workspace internal operation typically these are written to a http.Request
*/
type GetRecipeInWorkspaceInternalParams struct {

	/*AccountID*/
	AccountID *string
	/*Name*/
	Name string
	/*WorkspaceID*/
	WorkspaceID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) WithTimeout(timeout time.Duration) *GetRecipeInWorkspaceInternalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) WithContext(ctx context.Context) *GetRecipeInWorkspaceInternalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) WithHTTPClient(client *http.Client) *GetRecipeInWorkspaceInternalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) WithAccountID(accountID *string) *GetRecipeInWorkspaceInternalParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) SetAccountID(accountID *string) {
	o.AccountID = accountID
}

// WithName adds the name to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) WithName(name string) *GetRecipeInWorkspaceInternalParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) SetName(name string) {
	o.Name = name
}

// WithWorkspaceID adds the workspaceID to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) WithWorkspaceID(workspaceID int64) *GetRecipeInWorkspaceInternalParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the get recipe in workspace internal params
func (o *GetRecipeInWorkspaceInternalParams) SetWorkspaceID(workspaceID int64) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRecipeInWorkspaceInternalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccountID != nil {

		// query param accountId
		var qrAccountID string
		if o.AccountID != nil {
			qrAccountID = *o.AccountID
		}
		qAccountID := qrAccountID
		if qAccountID != "" {
			if err := r.SetQueryParam("accountId", qAccountID); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param workspaceId
	if err := r.SetPathParam("workspaceId", swag.FormatInt64(o.WorkspaceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
